"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { createContext, useCallback, useContext, useEffect, useState } from "react";
import { brandConfig } from "@/config/brand";
import { apiRequest } from "@/lib/api/client";
import { toApiError } from "@/lib/api/errors";
import { useDashboardWorkspace } from "@/features/dashboard-workspace/workspace-context";
import { useOperations } from "@/features/operations/operations-context";
import type { ContentCourse, ContentExam, ContentLesson, ContentPackage, CurriculumUnit, GradeEntry, StoreProduct, WebsiteContentItem } from "@/types/content";

type Value = { courses: ContentCourse[]; units: CurriculumUnit[]; lessons: ContentLesson[]; packages: ContentPackage[]; exams: ContentExam[]; grades: GradeEntry[]; products: StoreProduct[]; websiteItems: WebsiteContentItem[]; canSeeCourse: (id: string) => boolean; createCourse: (input: Omit<ContentCourse,"id"|"teacherId">)=>string|undefined; updateCourse:(id:string,input:Partial<ContentCourse>)=>string|undefined; setCourseState:(id:string,state:ContentCourse["state"])=>string|undefined; createUnit:(courseId:string,title:string)=>string|undefined; updateUnit:(id:string,title:string)=>string|undefined; reorderUnit:(id:string,direction:-1|1)=>string|undefined; setUnitState:(id:string,state:CurriculumUnit["state"])=>string|undefined; createLesson:(input:Omit<ContentLesson,"id"|"position"|"attachments">&{attachmentName?:string})=>string|undefined; updateLesson:(id:string,input:Partial<ContentLesson>)=>string|undefined; deleteLesson:(id:string)=>string|undefined; reorderLesson:(id:string,direction:-1|1)=>string|undefined; setLessonState:(id:string,state:ContentLesson["state"])=>string|undefined; createPackage:(input:Omit<ContentPackage,"id">)=>string|undefined; updatePackage:(id:string,input:Partial<ContentPackage>)=>string|undefined; archivePackage:(id:string)=>string|undefined; createExam:(input:Omit<ContentExam,"id">)=>string|undefined; updateExam:(id:string,input:Partial<ContentExam>)=>string|undefined; setExamState:(id:string,state:ContentExam["state"])=>string|undefined; setGrade:(examId:string,studentId:string,score:number|undefined,note?:string)=>string|undefined; createProduct:(input:Omit<StoreProduct,"id">)=>string|undefined; updateProduct:(id:string,input:Partial<StoreProduct>)=>string|undefined; archiveProduct:(id:string)=>string|undefined; createWebsiteItem:(input:Omit<WebsiteContentItem,"id"|"order">)=>string|undefined; updateWebsiteItem:(id:string,input:Partial<WebsiteContentItem>)=>string|undefined; reorderWebsiteItem:(id:string,direction:-1|1)=>string|undefined; };
const Context = createContext<Value | null>(null); const state = (value:string): "DRAFT"|"PUBLISHED"|"ARCHIVED" => value === "PUBLISHED" ? "PUBLISHED" : value === "ARCHIVED" ? "ARCHIVED" : "DRAFT";
const websiteTypeFromApi:Record<string,WebsiteContentItem["type"]>={HERO_BANNER:"HERO",FEATURED_TEACHERS:"FEATURED_TEACHER",FEATURED_COURSES:"FEATURED_COURSE",FINAL_REVISIONS:"REVISION",STORE_HIGHLIGHTS:"STORE_HIGHLIGHT",TESTIMONIALS:"TESTIMONIAL",NEWS:"NEWS",CTA:"CTA"};
const websiteTypeToApi:Record<WebsiteContentItem["type"],string>={HERO:"HERO_BANNER",FEATURED_TEACHER:"FEATURED_TEACHERS",FEATURED_COURSE:"FEATURED_COURSES",REVISION:"FINAL_REVISIONS",STORE_HIGHLIGHT:"STORE_HIGHLIGHTS",TESTIMONIAL:"TESTIMONIALS",NEWS:"NEWS",CTA:"CTA"};

export function ContentProvider({children}:{children:React.ReactNode}) {
  const workspace=useDashboardWorkspace(); const ops=useOperations(); const [courses,setCourses]=useState<ContentCourse[]>([]); const [units,setUnits]=useState<CurriculumUnit[]>([]); const [lessons,setLessons]=useState<ContentLesson[]>([]); const [packages,setPackages]=useState<ContentPackage[]>([]); const [exams,setExams]=useState<ContentExam[]>([]); const [grades,setGrades]=useState<GradeEntry[]>([]); const [products,setProducts]=useState<StoreProduct[]>([]); const [websiteItems,setWebsiteItems]=useState<WebsiteContentItem[]>([]); const [academic,setAcademic]=useState<any>({subjects:[],grades:[],terms:[]});
  const load=useCallback(async()=>{
    const has=(permission:string)=>workspace.permissions.includes(permission as never);
    const [courseRaw,packageRaw,examRaw,paperRaw,productRaw,websiteRaw,academicRaw]=await Promise.all([
      has("courses.view")?apiRequest<any[]>("courses"):[], has("packages.view")?apiRequest<any[]>("packages"):[], has("exams.view")?apiRequest<any[]>("exams"):[], has("exams.view")?apiRequest<any[]>("paper-exams"):[], has("store.view")?apiRequest<any[]>("store/products"):[], workspace.role==="SUPER_ADMIN"&&has("website.view")?apiRequest<any[]>("website-content"):[], has("courses.view")?apiRequest<any>("academic-catalog"):{subjects:[],grades:[],terms:[]},
    ]);
    const details=await Promise.all(courseRaw.map((x)=>apiRequest<any>(`courses/${x.id}`)));
    const examDetails=await Promise.all(examRaw.map((x)=>apiRequest<any>(`exams/${x.id}`)));
    setCourses(courseRaw.map((x)=>({id:x.id,title:x.title,teacherId:x.teacherId,subject:x.subject?.name??x.subjectId,grade:x.grade?.name??x.gradeId,term:x.term?.name??x.termId,studyMode:x.studyMode??"HYBRID",state:state(x.status),description:x.description??"",coverImage:x.coverImage??undefined})));
    setUnits(details.flatMap((c)=> (c.units??[]).map((x:any)=>({id:x.id,courseId:c.id,title:x.title,position:x.position,state:state(x.status)}))));
    setLessons(details.flatMap((c)=>(c.units??[]).flatMap((u:any)=>(u.lessons??[]).map((x:any)=>({id:x.id,courseId:c.id,unitId:u.id,title:x.title,description:x.description??"",durationMinutes:Math.round((x.durationSeconds??0)/60),freePreview:Boolean(x.isFreePreview),state:state(x.status),position:x.position,attachments:(x.attachments??[]).map((a:any)=>({id:a.id,name:a.title,safePreviewLabel:a.title})),provider:x.videoProvider?"YOUTUBE":undefined,providerVideoId:x.providerVideoId??undefined,thumbnailUrl:x.thumbnailUrl??undefined})))));
    setPackages(packageRaw.map((x)=>({id:x.id,courseId:x.courseId,title:x.title,type:x.type,price:Number(x.price),accessDays:x.accessDurationDays??undefined,lessonIds:(x.lessons??[]).map((y:any)=>y.lessonId??y.id),includeFutureLessons:Boolean(x.includeFutureLessons),examIds:(x.exams??[]).map((y:any)=>y.examId??y.id),fileLabels:[],state:state(x.status),thumbnailUrl:x.thumbnailUrl??undefined})));
    const online=examDetails.map((x)=>{const assignment=x.assignments?.[0];const audience=assignment?.audience==="ALL_COURSE_STUDENTS"?"COURSE_STUDENTS":assignment?.audience==="CENTER_GROUP"?"GROUPS":assignment?.audience??"COURSE_STUDENTS";const targetIds=assignment?.audience==="CENTER_GROUP"?[assignment.groupId]:assignment?.audience==="SELECTED_STUDENTS"?(assignment.students??[]).map((item:any)=>item.studentId):[];return {id:x.id,courseId:x.courseId,title:x.title,kind:"ONLINE" as const,durationMinutes:x.durationMinutes,attempts:x.maxAttempts,availableFrom:x.availableFrom??undefined,availableTo:x.availableUntil??undefined,passingScore:x.passingScore==null?undefined:Number(x.passingScore),resultRelease:x.releaseMode==="MANUAL"?"AFTER_REVIEW" as const:x.releaseMode==="AFTER_WINDOW"?"SCHEDULED" as const:"IMMEDIATE" as const,antiCheatThreshold:x.violationThreshold??undefined,audience,targetIds,questions:(x.questions??[]).map((q:any)=>({id:q.id,prompt:q.prompt,type:q.type,choices:Array.isArray(q.options)?q.options:undefined,correctAnswers:Array.isArray(q.correctAnswer)?q.correctAnswer:undefined})),state:state(x.status),assignmentId:assignment?.id};});
    const paper=paperRaw.map((x)=>({id:x.id,courseId:x.courseId,title:x.title,kind:"PAPER" as const,passingScore:undefined,resultRelease:"AFTER_REVIEW" as const,audience:"CENTER_STUDENTS" as const,targetIds:[],questions:[],state:state(x.status)}));
    setExams([...online,...paper]);
    setGrades(paperRaw.flatMap((exam)=>(exam.results??[]).map((result:any)=>({id:result.id,examId:exam.id,studentId:result.studentId,score:result.score==null?undefined:Number(result.score),manualReview:result.status!=="GRADED",note:result.notes??undefined}))));
    setProducts(productRaw.map((x)=>({id:x.id,type:x.type,title:x.title,coverAlt:x.previewMetadata?.coverAlt??x.title,imageUrl:x.imageUrl??undefined,teacherOrPublisher:x.previewMetadata?.teacherOrPublisher??brandConfig.name,grade:x.previewMetadata?.grade??"",subject:x.previewMetadata?.subject??"",description:x.description??"",pageCount:x.previewMetadata?.pageCount??undefined,format:x.previewMetadata?.format??"",price:x.price==null?undefined:Number(x.price),relatedCourseId:x.courseId??undefined,relatedPackageId:x.packageId??undefined,state:state(x.status),safePreviewLabel:x.previewMetadata?.safePreviewLabel??undefined})));
    setWebsiteItems(websiteRaw.map((x)=>({id:x.id,type:websiteTypeFromApi[x.type]??"CTA",title:x.title??"",subtitle:x.subtitle??undefined,body:x.body??undefined,imageUrl:x.imageUrl??undefined,mobileImageUrl:x.metadata?.mobileImageUrl??undefined,order:x.position,active:x.isActive,imageAlt:x.metadata?.imageAlt??undefined,desktopImageAlt:x.metadata?.desktopImageAlt??undefined,mobileImageAlt:x.metadata?.mobileImageAlt??undefined,ctaLabel:x.ctaLabel??undefined,ctaLink:x.ctaUrl??undefined,startsAt:x.startsAt??undefined,endsAt:x.endsAt??undefined,teacherId:x.metadata?.teacherId??undefined,courseId:x.metadata?.courseId??undefined,storeProductId:x.metadata?.storeProductId??undefined})));
    setAcademic(academicRaw);
  },[workspace.permissions,workspace.role]);
  useEffect(()=>{void load().catch((error)=>window.alert(toApiError(error).message));},[load]); const refresh=()=>{void load();}; const mutate=(path:string,method:string,body?:unknown)=>{void apiRequest(path,{method,body}).then(refresh).catch((error)=>window.alert(toApiError(error).message));}; const canSeeCourse=(id:string)=>{const c=courses.find((x)=>x.id===id);return Boolean(c&&ops.canSeeTeacher(c.teacherId));}; const ids=(input:Partial<ContentCourse>)=>({subjectId:academic.subjects?.find((x:any)=>x.name===input.subject)?.id,gradeId:academic.grades?.find((x:any)=>x.name===input.grade)?.id,termId:academic.terms?.find((x:any)=>x.name===input.term)?.id});
  const createCourse=(input:Omit<ContentCourse,"id"|"teacherId">)=>{const teacherId=workspace.user.teacherId??workspace.assignment?.teacherId??ops.teachers[0]?.id; const found=ids(input); if(!teacherId||!found.subjectId||!found.gradeId||!found.termId)return "تعذر مطابقة المدرس أو المادة أو الصف أو الفصل بالكتالوج الأكاديمي."; mutate("courses","POST",{teacherId,...found,title:input.title,slug:`course-${Date.now().toString(36)}`,description:input.description,studyMode:input.studyMode,coverImage:input.coverImage});return undefined;}; const updateCourse=(id:string,input:Partial<ContentCourse>)=>{mutate(`courses/${id}`,"PATCH",{title:input.title,description:input.description,studyMode:input.studyMode,coverImage:input.coverImage,...ids(input)});return undefined;}; const setCourseState=(id:string,s:ContentCourse["state"])=>{mutate(`courses/${id}/${s==="PUBLISHED"?"publish":s==="ARCHIVED"?"archive":"unpublish"}`,"POST");return undefined;};
  const createUnit=(courseId:string,title:string)=>{mutate(`courses/${courseId}/units`,"POST",{title});return undefined;}; const updateUnit=(id:string,title:string)=>{mutate(`courses/units/${id}`,"PATCH",{title});return undefined;}; const reorderUnit=(id:string,direction:-1|1)=>{const item=units.find(x=>x.id===id);if(!item)return "الوحدة غير موجودة.";const ordered=units.filter(x=>x.courseId===item.courseId).sort((a,b)=>a.position-b.position);const index=ordered.findIndex(x=>x.id===id);const swap=ordered[index+direction];if(!swap)return "لا يمكن نقل الوحدة أكثر.";const next=[...ordered];[next[index],next[index+direction]]=[next[index+direction],next[index]];mutate(`courses/${item.courseId}/units/reorder`,"POST",{items:next.map((x,position)=>({id:x.id,position}))});return undefined;}; const setUnitState=(id:string,s:CurriculumUnit["state"])=>{mutate(`courses/units/${id}/${s==="PUBLISHED"?"publish":s==="ARCHIVED"?"archive":"unpublish"}`,"POST");return undefined;};
  const createLesson=(input:Omit<ContentLesson,"id"|"position"|"attachments">&{attachmentName?:string})=>{void apiRequest<any>(`courses/${input.courseId}/lessons`,{method:"POST",body:{unitId:input.unitId,title:input.title,description:input.description,durationSeconds:input.durationMinutes*60,isFreePreview:input.freePreview,youtubeUrl:input.youtubeUrl,thumbnailUrl:input.thumbnailUrl}}).then(async(lesson)=>{if(input.attachmentName)await apiRequest(`courses/lessons/${lesson.id}/attachments`,{method:"POST",body:{title:input.attachmentName}});await load();}).catch((error)=>window.alert(toApiError(error).message));return undefined;}; const updateLesson=(id:string,input:Partial<ContentLesson>)=>{mutate(`courses/lessons/${id}`,"PATCH",{title:input.title,description:input.description,durationSeconds:input.durationMinutes===undefined?undefined:input.durationMinutes*60,isFreePreview:input.freePreview,youtubeUrl:input.youtubeUrl,thumbnailUrl:input.thumbnailUrl});return undefined;}; const deleteLesson=(id:string)=>{mutate(`courses/lessons/${id}`,"DELETE");return undefined;}; const setLessonState=(id:string,s:ContentLesson["state"])=>{mutate(`courses/lessons/${id}/${s==="PUBLISHED"?"publish":s==="ARCHIVED"?"archive":"unpublish"}`,"POST");return undefined;}; const reorderLesson=(id:string,direction:-1|1)=>{const item=lessons.find(x=>x.id===id);if(!item)return "الدرس غير موجود.";const ordered=lessons.filter(x=>x.courseId===item.courseId).sort((a,b)=>a.position-b.position);const index=ordered.findIndex(x=>x.id===id);if(!ordered[index+direction])return "لا يمكن نقل الدرس أكثر.";const next=[...ordered];[next[index],next[index+direction]]=[next[index+direction],next[index]];mutate(`courses/${item.courseId}/lessons/reorder`,"POST",{items:next.map((x,position)=>({id:x.id,position}))});return undefined;};
  const packageBody=(x:Partial<ContentPackage>)=>({courseId:x.courseId,title:x.title,type:x.type,price:x.price,accessDurationDays:x.accessDays,includeFutureLessons:x.includeFutureLessons,lessonIds:x.lessonIds,examIds:x.examIds,thumbnailUrl:x.thumbnailUrl}); const createPackage=(input:Omit<ContentPackage,"id">)=>{if(input.fileLabels.length)return "الخادم يربط ملفات الباقة بمعرّفات مرفقات، وليس بأسماء ملفات؛ أزل الأسماء أو وفّر عقد اختيار المرفقات.";mutate("packages","POST",packageBody(input));return undefined;}; const updatePackage=(id:string,input:Partial<ContentPackage>)=>{if(input.fileLabels?.length)return "الخادم يربط ملفات الباقة بمعرّفات مرفقات، وليس بأسماء ملفات؛ لن تُحفظ أسماء محلية بديلة.";mutate(`packages/${id}`,"PATCH",packageBody(input));return undefined;}; const archivePackage=(id:string)=>{mutate(`packages/${id}/archive`,"POST");return undefined;};
  const releaseMode=(value:ContentExam["resultRelease"]|undefined)=>value==="AFTER_REVIEW"?"MANUAL":value==="SCHEDULED"?"AFTER_WINDOW":"IMMEDIATE"; const assignmentBody=(input:Partial<ContentExam>)=>input.audience==="GROUPS"?{audience:"CENTER_GROUP",groupId:input.targetIds?.[0]}:input.audience==="SELECTED_STUDENTS"?{audience:"SELECTED_STUDENTS",studentIds:input.targetIds}: {audience:input.audience==="COURSE_STUDENTS"?"ALL_COURSE_STUDENTS":input.audience};
  const createExam=(input:Omit<ContentExam,"id">)=>{
    if(input.kind==="PAPER"){mutate("paper-exams","POST",{courseId:input.courseId,title:input.title,maxScore:100});return undefined;}
    void apiRequest<any>("exams",{method:"POST",body:{courseId:input.courseId,title:input.title,durationMinutes:input.durationMinutes,maxAttempts:input.attempts,maxScore:100,availableFrom:input.availableFrom||undefined,availableUntil:input.availableTo||undefined,passingScore:input.passingScore,releaseMode:releaseMode(input.resultRelease),violationThreshold:input.antiCheatThreshold}}).then(async(exam)=>{for(const q of input.questions)await apiRequest(`exams/${exam.id}/questions`,{method:"POST",body:{prompt:q.prompt,type:q.type,options:q.choices,correctAnswer:q.correctAnswers,points:1}});for(const target of input.audience==="GROUPS"?input.targetIds:[undefined])await apiRequest(`exams/${exam.id}/assignments`,{method:"POST",body:input.audience==="GROUPS"?{audience:"CENTER_GROUP",groupId:target}:assignmentBody(input)});await load();}).catch((error)=>window.alert(toApiError(error).message));return undefined;
  };
  const updateExam=(id:string,input:Partial<ContentExam>)=>{const current=exams.find((item)=>item.id===id);if(current?.kind==="PAPER")return "تعديل تعريف الاختبار الورقي غير معروض في العقد الحالي؛ يمكن إدخال درجاته ونشره.";void apiRequest(`exams/${id}`,{method:"PATCH",body:{title:input.title,durationMinutes:input.durationMinutes,maxAttempts:input.attempts,maxScore:100,availableFrom:input.availableFrom||undefined,availableUntil:input.availableTo||undefined,passingScore:input.passingScore,releaseMode:releaseMode(input.resultRelease),violationThreshold:input.antiCheatThreshold}}).then(async()=>{const question=input.questions?.[0];const existing=current?.questions[0];if(question&&existing)await apiRequest(`exams/questions/${existing.id}`,{method:"PATCH",body:{prompt:question.prompt,type:question.type,options:question.choices,correctAnswer:question.correctAnswers,points:1}});if(input.audience!==undefined){if(current?.assignmentId)await apiRequest(`exams/assignments/${current.assignmentId}`,{method:"PATCH",body:assignmentBody(input)});else await apiRequest(`exams/${id}/assignments`,{method:"POST",body:assignmentBody(input)});}await load();}).catch((error)=>window.alert(toApiError(error).message));return undefined;};
  const setExamState=(id:string,s:ContentExam["state"])=>{const exam=exams.find((item)=>item.id===id);mutate(`${exam?.kind==="PAPER"?"paper-exams":"exams"}/${id}/${s==="PUBLISHED"?"publish":"archive"}`,"POST");return undefined;};
  const setGrade=(examId:string,studentId:string,score:number|undefined,note?:string)=>{const exam=exams.find((item)=>item.id===examId);if(exam?.kind!=="PAPER")return "الدرجات الإلكترونية تُحسب من محاولات الاختبار ولا تُكتب يدويًا من هذه الصفحة.";mutate(`paper-exams/${examId}/results`,"POST",{studentId,status:score===undefined?"NOT_SUBMITTED":"GRADED",score,notes:note});return undefined;};
  const productBody=(x:Partial<StoreProduct>)=>({type:x.type,title:x.title,description:x.description,imageUrl:x.imageUrl,price:x.price??0,isFree:x.price===undefined||x.price===0,courseId:x.relatedCourseId,packageId:x.relatedPackageId,previewMetadata:{coverAlt:x.coverAlt,teacherOrPublisher:x.teacherOrPublisher,grade:x.grade,subject:x.subject,pageCount:x.pageCount,format:x.format,safePreviewLabel:x.safePreviewLabel}}); const createProduct=(x:Omit<StoreProduct,"id">)=>{mutate("store/products","POST",productBody(x));return undefined;};const updateProduct=(id:string,x:Partial<StoreProduct>)=>{mutate(`store/products/${id}`,"PATCH",productBody(x));return undefined;};const archiveProduct=(id:string)=>{mutate(`store/products/${id}/archive`,"POST");return undefined;}; const websiteBody=(x:Partial<WebsiteContentItem>)=>({type:x.type?websiteTypeToApi[x.type]:undefined,title:x.title,subtitle:x.subtitle,body:x.body,imageUrl:x.imageUrl,position:x.order,isActive:x.active,ctaLabel:x.ctaLabel,ctaUrl:x.ctaLink,startsAt:x.startsAt||undefined,endsAt:x.endsAt||undefined,metadata:{imageAlt:x.imageAlt,desktopImageAlt:x.desktopImageAlt,mobileImageAlt:x.mobileImageAlt,mobileImageUrl:x.mobileImageUrl,teacherId:x.teacherId,courseId:x.courseId,storeProductId:x.storeProductId}}); const createWebsiteItem=(x:Omit<WebsiteContentItem,"id"|"order">)=>{mutate("website-content","POST",websiteBody({...x,order:websiteItems.length+1}));return undefined;};const updateWebsiteItem=(id:string,x:Partial<WebsiteContentItem>)=>{const current=websiteItems.find((item)=>item.id===id);mutate(`website-content/${id}`,"PATCH",websiteBody(current?{...current,...x}:x));return undefined;};const reorderWebsiteItem=(id:string,direction:-1|1)=>{const ordered=[...websiteItems].sort((a,b)=>a.order-b.order);const index=ordered.findIndex((item)=>item.id===id);if(index<0||!ordered[index+direction])return "لا يمكن نقل عنصر الموقع أكثر.";[ordered[index],ordered[index+direction]]=[ordered[index+direction],ordered[index]];mutate("website-content/reorder","POST",{items:ordered.map((item,position)=>({id:item.id,position}))});return undefined;};
  const exposedProducts=products.map((item)=>item.price===0?{...item,price:undefined}:item); const exposedWebsiteItems=websiteItems.map((item)=>({...item,type:websiteTypeFromApi[item.type]??item.type}));
  return <Context.Provider value={{courses,units,lessons,packages,exams,grades,products:exposedProducts,websiteItems:exposedWebsiteItems,canSeeCourse,createCourse,updateCourse,setCourseState,createUnit,updateUnit,reorderUnit,setUnitState,createLesson,updateLesson,deleteLesson,reorderLesson,setLessonState,createPackage,updatePackage,archivePackage,createExam,updateExam,setExamState,setGrade,createProduct,updateProduct,archiveProduct,createWebsiteItem,updateWebsiteItem,reorderWebsiteItem}}>{children}</Context.Provider>;
}
export function useContent(){const value=useContext(Context);if(!value)throw new Error("useContent must be used within ContentProvider");return value;}
