"use client";

import { createContext, useContext, useState } from "react";
import { canAccess } from "@/lib/access-control";
import { useDashboardWorkspace } from "@/features/dashboard-workspace/workspace-context";
import { useOperations } from "@/features/operations/operations-context";
import { initialContentCourses, initialExams, initialGrades, initialLessons, initialPackages, initialStoreProducts, initialUnits, initialWebsiteContent } from "@/mocks/repositories/mock-content-repository";
import type { ContentCourse, ContentExam, ContentLesson, ContentPackage, CurriculumUnit, GradeEntry, StoreProduct, WebsiteContentItem } from "@/types/content";

type ContentContextValue = {
  courses: ContentCourse[]; units: CurriculumUnit[]; lessons: ContentLesson[]; packages: ContentPackage[]; exams: ContentExam[]; grades: GradeEntry[]; products: StoreProduct[]; websiteItems: WebsiteContentItem[];
  canSeeCourse: (courseId: string) => boolean; createCourse: (input: Omit<ContentCourse, "id" | "teacherId">) => string | undefined; updateCourse: (id: string, input: Partial<ContentCourse>) => string | undefined; setCourseState: (id: string, state: ContentCourse["state"]) => string | undefined;
  createUnit: (courseId: string, title: string) => string | undefined; updateUnit: (id: string, title: string) => string | undefined; reorderUnit: (id: string, direction: -1 | 1) => string | undefined; setUnitState: (id: string, state: CurriculumUnit["state"]) => string | undefined;
  createLesson: (input: Omit<ContentLesson, "id" | "position" | "attachments"> & { attachmentName?: string }) => string | undefined; updateLesson: (id: string, input: Partial<ContentLesson>) => string | undefined; deleteLesson: (id: string) => string | undefined; reorderLesson: (id: string, direction: -1 | 1) => string | undefined; setLessonState: (id: string, state: ContentLesson["state"]) => string | undefined;
  createPackage: (input: Omit<ContentPackage, "id">) => string | undefined; updatePackage: (id: string, input: Partial<ContentPackage>) => string | undefined; archivePackage: (id: string) => string | undefined;
  createExam: (input: Omit<ContentExam, "id">) => string | undefined; updateExam: (id: string, input: Partial<ContentExam>) => string | undefined; setExamState: (id: string, state: ContentExam["state"]) => string | undefined; setGrade: (examId: string, studentId: string, score: number | undefined, note?: string) => string | undefined;
  createProduct: (input: Omit<StoreProduct, "id">) => string | undefined; updateProduct: (id: string, input: Partial<StoreProduct>) => string | undefined; archiveProduct: (id: string) => string | undefined;
  createWebsiteItem: (input: Omit<WebsiteContentItem, "id" | "order">) => string | undefined; updateWebsiteItem: (id: string, input: Partial<WebsiteContentItem>) => string | undefined; reorderWebsiteItem: (id: string, direction: -1 | 1) => string | undefined;
};
const ContentContext = createContext<ContentContextValue | null>(null);
const makeId = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;

export function ContentProvider({ children }: { children: React.ReactNode }) {
  const { role, user, permissions, assignment } = useDashboardWorkspace();
  const ops = useOperations();
  const [courses, setCourses] = useState(initialContentCourses); const [units, setUnits] = useState(initialUnits); const [lessons, setLessons] = useState(initialLessons); const [packages, setPackages] = useState(initialPackages); const [exams, setExams] = useState(initialExams); const [grades, setGrades] = useState(initialGrades); const [products, setProducts] = useState(initialStoreProducts); const [websiteItems, setWebsiteItems] = useState(initialWebsiteContent);
  const allowed = (permission: Parameters<typeof canAccess>[1]) => canAccess(role, permission, permissions);
  const courseFor = (id: string) => courses.find((course) => course.id === id);
  const canSeeCourse = (courseId: string) => { const course = courseFor(courseId); return Boolean(course && ops.canSeeTeacher(course.teacherId)); };
  const audit = (action: string, targetId: string, courseId?: string) => { const course = courseId ? courseFor(courseId) : undefined; ops.recordContentAudit(action, targetId, course?.teacherId); };
  const scoped = (courseId: string, permission: Parameters<typeof canAccess>[1]) => allowed(permission) && canSeeCourse(courseId);

  function createCourse(input: Omit<ContentCourse, "id" | "teacherId">) { if (!allowed("courses.manage")) return "لا تملك صلاحية إدارة الكورسات."; const teacherId = role === "SUPER_ADMIN" ? ops.teachers.find((teacher) => teacher.subject === input.subject)?.id ?? ops.teachers[0].id : user.teacherId ?? assignment?.teacherId; if (!teacherId) return "تعذر تحديد نطاق المدرس."; const newCourse = { ...input, id: makeId("course"), teacherId }; setCourses((items) => [newCourse, ...items]); audit("COURSE_CREATED", newCourse.id, newCourse.id); return undefined; }
  function updateCourse(id: string, input: Partial<ContentCourse>) { if (!scoped(id, "courses.manage")) return "الكورس غير موجود أو خارج نطاقك."; setCourses((items) => items.map((item) => item.id === id ? { ...item, ...input, id: item.id, teacherId: item.teacherId } : item)); audit("COURSE_UPDATED", id, id); return undefined; }
  function setCourseState(id: string, state: ContentCourse["state"]) { const result = updateCourse(id, { state }); if (!result) audit(state === "ARCHIVED" ? "COURSE_ARCHIVED" : `COURSE_${state}`, id, id); return result; }
  function createUnit(courseId: string, title: string) { if (!scoped(courseId, "lessons.manage") || !title.trim()) return "تحقق من الصلاحية واسم الوحدة."; const unit = { id: makeId("unit"), courseId, title: title.trim(), position: units.filter((item) => item.courseId === courseId).length + 1, state: "DRAFT" as const }; setUnits((items) => [...items, unit]); audit("UNIT_CREATED", unit.id, courseId); return undefined; }
  function updateUnit(id: string, title: string) { const unit = units.find((item) => item.id === id); if (!unit || !scoped(unit.courseId, "lessons.manage") || !title.trim()) return "الوحدة غير صالحة أو خارج نطاقك."; setUnits((items) => items.map((item) => item.id === id ? { ...item, title: title.trim() } : item)); audit("UNIT_UPDATED", id, unit.courseId); return undefined; }
  function setUnitState(id: string, state: CurriculumUnit["state"]) { const unit = units.find((item) => item.id === id); if (!unit || !scoped(unit.courseId, "lessons.manage")) return "الوحدة غير موجودة أو خارج نطاقك."; setUnits((items) => items.map((item) => item.id === id ? { ...item, state } : item)); audit(`UNIT_${state}`, id, unit.courseId); return undefined; }
  function reorderUnit(id: string, direction: -1 | 1) { const unit = units.find((item) => item.id === id); if (!unit || !scoped(unit.courseId, "lessons.manage")) return "الوحدة غير موجودة أو خارج نطاقك."; const siblings = units.filter((item) => item.courseId === unit.courseId).sort((a, b) => a.position - b.position); const index = siblings.findIndex((item) => item.id === id); const swap = siblings[index + direction]; if (!swap) return "لا يمكن نقل الوحدة أكثر."; setUnits((items) => items.map((item) => item.id === unit.id ? { ...item, position: swap.position } : item.id === swap.id ? { ...item, position: unit.position } : item)); audit("UNIT_REORDERED", id, unit.courseId); return undefined; }
  function createLesson(input: Omit<ContentLesson, "id" | "position" | "attachments"> & { attachmentName?: string }) { if (!scoped(input.courseId, "lessons.manage") || !units.some((unit) => unit.id === input.unitId && unit.courseId === input.courseId) || !input.title.trim() || input.durationMinutes <= 0) return "تحقق من الدرس والوحدة والمدة."; const lesson: ContentLesson = { ...input, id: makeId("lesson"), position: lessons.filter((item) => item.unitId === input.unitId).length + 1, attachments: input.attachmentName?.trim() ? [{ id: makeId("attachment"), name: input.attachmentName.trim(), safePreviewLabel: "معاينة آمنة" }] : [] }; delete (lesson as ContentLesson & { attachmentName?: string }).attachmentName; setLessons((items) => [...items, lesson]); audit("LESSON_CREATED", lesson.id, lesson.courseId); return undefined; }
  function updateLesson(id: string, input: Partial<ContentLesson>) { const lesson = lessons.find((item) => item.id === id); if (!lesson || !scoped(lesson.courseId, "lessons.manage")) return "الدرس غير موجود أو خارج نطاقك."; setLessons((items) => items.map((item) => item.id === id ? { ...item, ...input, id: item.id, courseId: item.courseId, unitId: item.unitId } : item)); audit("LESSON_UPDATED", id, lesson.courseId); return undefined; }
  function deleteLesson(id: string) { const lesson = lessons.find((item) => item.id === id); if (!lesson || !scoped(lesson.courseId, "lessons.manage")) return "الدرس غير موجود أو خارج نطاقك."; if (packages.some((item) => item.lessonIds.includes(id))) return "الدرس مرتبط بباقة؛ أرشف الباقة أو عدّل نطاقها أولًا."; setLessons((items) => items.filter((item) => item.id !== id)); audit("LESSON_DELETED", id, lesson.courseId); return undefined; }
  function setLessonState(id: string, state: ContentLesson["state"]) { const lesson = lessons.find((item) => item.id === id); if (!lesson || !scoped(lesson.courseId, "lessons.manage")) return "الدرس غير موجود أو خارج نطاقك."; setLessons((items) => items.map((item) => item.id === id ? { ...item, state } : item)); audit(`LESSON_${state}`, id, lesson.courseId); return undefined; }
  function reorderLesson(id: string, direction: -1 | 1) { const lesson = lessons.find((item) => item.id === id); if (!lesson || !scoped(lesson.courseId, "lessons.manage")) return "الدرس غير موجود أو خارج نطاقك."; const siblings = lessons.filter((item) => item.unitId === lesson.unitId).sort((a, b) => a.position - b.position); const swap = siblings[siblings.findIndex((item) => item.id === id) + direction]; if (!swap) return "لا يمكن نقل الدرس أكثر."; setLessons((items) => items.map((item) => item.id === id ? { ...item, position: swap.position } : item.id === swap.id ? { ...item, position: lesson.position } : item)); audit("LESSON_REORDERED", id, lesson.courseId); return undefined; }
  function validPackage(input: Partial<ContentPackage>) { const courseId = input.courseId; return Boolean(courseId && input.lessonIds?.every((lessonId) => lessons.some((lesson) => lesson.id === lessonId && lesson.courseId === courseId)) && input.examIds?.every((examId) => exams.some((exam) => exam.id === examId && exam.courseId === courseId)) && (input.type === "TERM" || !input.includeFutureLessons)); }
  function createPackage(input: Omit<ContentPackage, "id">) { if (!scoped(input.courseId, "packages.manage") || !input.title.trim() || input.price < 0 || !validPackage(input)) return "تحقق من نطاق الدروس والاختبارات وإعداد الباقة."; const item = { ...input, id: makeId("package") }; setPackages((items) => [item, ...items]); audit("PACKAGE_CREATED", item.id, item.courseId); return undefined; }
  function updatePackage(id: string, input: Partial<ContentPackage>) { const item = packages.find((candidate) => candidate.id === id); const next = item && { ...item, ...input }; if (!item || !next || !scoped(item.courseId, "packages.manage") || !validPackage(next)) return "الباقة غير صالحة أو خارج نطاقك."; setPackages((items) => items.map((candidate) => candidate.id === id ? next : candidate)); audit(input.price !== undefined ? "PACKAGE_PRICE_CHANGED" : "PACKAGE_UPDATED", id, item.courseId); return undefined; }
  function archivePackage(id: string) { return updatePackage(id, { state: "ARCHIVED" }); }
  function createExam(input: Omit<ContentExam, "id">) { if (!scoped(input.courseId, "exams.manage") || !input.title.trim() || (input.kind === "ONLINE" && (!input.durationMinutes || !input.attempts)) || input.questions.some((question) => question.type !== "SHORT_TEXT" && !question.correctAnswers?.length)) return "تحقق من إعدادات الاختبار والإجابات الموضوعية."; const exam = { ...input, id: makeId("exam") }; setExams((items) => [exam, ...items]); audit("EXAM_CREATED", exam.id, exam.courseId); return undefined; }
  function updateExam(id: string, input: Partial<ContentExam>) { const exam = exams.find((item) => item.id === id); const next = exam && { ...exam, ...input }; if (!exam || !next || !scoped(exam.courseId, "exams.manage")) return "الاختبار غير موجود أو خارج نطاقك."; setExams((items) => items.map((item) => item.id === id ? next : item)); audit("EXAM_UPDATED", id, exam.courseId); return undefined; }
  function setExamState(id: string, state: ContentExam["state"]) { const exam = exams.find((item) => item.id === id); if (!exam) return "الاختبار غير موجود."; const result = updateExam(id, { state }); if (!result) audit(`EXAM_${state}`, id, exam.courseId); return result; }
  function setGrade(examId: string, studentId: string, score: number | undefined, note?: string) { const exam = exams.find((item) => item.id === examId); if (!exam || !scoped(exam.courseId, "grades.manage") || (score !== undefined && (score < 0 || score > 100))) return "الدرجة غير صالحة أو خارج نطاقك."; setGrades((items) => { const found = items.find((item) => item.examId === examId && item.studentId === studentId); return found ? items.map((item) => item.id === found.id ? { ...item, score, note, manualReview: true } : item) : [...items, { id: makeId("grade"), examId, studentId, score, note, manualReview: true }]; }); audit("GRADE_CHANGED", `${examId}:${studentId}`, exam.courseId); return undefined; }
  function createProduct(input: Omit<StoreProduct, "id">) { if (!allowed("store.manage") || !input.title.trim() || (input.relatedCourseId && !canSeeCourse(input.relatedCourseId))) return "تحقق من بيانات المنتج ونطاق الكورس."; const product = { ...input, id: makeId("store") }; setProducts((items) => [product, ...items]); audit("STORE_PRODUCT_CREATED", product.id, product.relatedCourseId); return undefined; }
  function updateProduct(id: string, input: Partial<StoreProduct>) { const product = products.find((item) => item.id === id); if (!product || !allowed("store.manage") || (product.relatedCourseId && !canSeeCourse(product.relatedCourseId))) return "المنتج غير موجود أو خارج نطاقك."; setProducts((items) => items.map((item) => item.id === id ? { ...item, ...input, id: item.id } : item)); audit("STORE_PRODUCT_UPDATED", id, product.relatedCourseId); return undefined; }
  function archiveProduct(id: string) { const product = products.find((item) => item.id === id); const result = updateProduct(id, { state: "ARCHIVED" }); if (!result && product) audit("STORE_PRODUCT_ARCHIVED", id, product.relatedCourseId); return result; }
  function createWebsiteItem(input: Omit<WebsiteContentItem, "id" | "order">) { if (!allowed("website.manage") || (input.courseId && !courses.some((course) => course.id === input.courseId)) || (input.teacherId && !ops.teachers.some((teacher) => teacher.id === input.teacherId))) return "تحقق من الصلاحية ومعرّف الكورس أو المدرس في الكتالوج."; const item = { ...input, id: makeId("website"), order: websiteItems.length + 1 }; setWebsiteItems((items) => [...items, item]); audit("WEBSITE_CONTENT_CREATED", item.id, item.courseId); return undefined; }
  function updateWebsiteItem(id: string, input: Partial<WebsiteContentItem>) { const item = websiteItems.find((candidate) => candidate.id === id); if (!item || !allowed("website.manage")) return "عنصر الموقع غير موجود أو لا تملك صلاحية تعديله."; setWebsiteItems((items) => items.map((candidate) => candidate.id === id ? { ...candidate, ...input, id: candidate.id, order: candidate.order } : candidate)); audit("WEBSITE_CONTENT_CHANGED", id, item.courseId); return undefined; }
  function reorderWebsiteItem(id: string, direction: -1 | 1) { const item = websiteItems.find((candidate) => candidate.id === id); if (!item || !allowed("website.manage")) return "عنصر الموقع غير موجود أو لا تملك صلاحية تعديله."; const ordered = [...websiteItems].sort((a, b) => a.order - b.order); const swap = ordered[ordered.findIndex((candidate) => candidate.id === id) + direction]; if (!swap) return "لا يمكن نقل العنصر أكثر."; setWebsiteItems((items) => items.map((candidate) => candidate.id === item.id ? { ...candidate, order: swap.order } : candidate.id === swap.id ? { ...candidate, order: item.order } : candidate)); audit("WEBSITE_CONTENT_REORDERED", id, item.courseId); return undefined; }
  return <ContentContext.Provider value={{ courses, units, lessons, packages, exams, grades, products, websiteItems, canSeeCourse, createCourse, updateCourse, setCourseState, createUnit, updateUnit, reorderUnit, setUnitState, createLesson, updateLesson, deleteLesson, reorderLesson, setLessonState, createPackage, updatePackage, archivePackage, createExam, updateExam, setExamState, setGrade, createProduct, updateProduct, archiveProduct, createWebsiteItem, updateWebsiteItem, reorderWebsiteItem }}>{children}</ContentContext.Provider>;
}
export function useContent() { const context = useContext(ContentContext); if (!context) throw new Error("useContent must be used within ContentProvider"); return context; }
