import type { DashboardRole } from "@/types/auth";
import type { Permission } from "@/types/permissions";

export const ALL_PERMISSIONS = [
  "dashboard.view",
  "students.view",
  "students.create",
  "students.update",
  "students.view_guardian",
  "guardians.view",
  "guardians.contact",
  "scanner.use",
  "attendance.view",
  "attendance.create",
  "attendance.update",
  "attendance.override",
  "courses.view",
  "courses.manage",
  "groups.view",
  "groups.manage",
  "content.manage",
  "exams.view",
  "exams.manage",
  "results.view",
  "results.manage",
  "teachers.view",
  "teachers.manage",
  "assistants.view",
  "assistants.manage",
  "subscriptions.view",
  "subscriptions.manage",
  "payments.view",
  "payments.manage",
  "reports.view",
  "settings.center",
  "settings.system",
  "audit.view",
  "users.manage",
  "permissions.manage",
] as const satisfies readonly Permission[];

const adminPermissions = [
  "dashboard.view",
  "students.view",
  "students.create",
  "students.update",
  "students.view_guardian",
  "guardians.view",
  "guardians.contact",
  "scanner.use",
  "attendance.view",
  "attendance.create",
  "attendance.update",
  "attendance.override",
  "courses.view",
  "courses.manage",
  "groups.view",
  "groups.manage",
  "exams.view",
  "results.view",
  "teachers.view",
  "teachers.manage",
  "assistants.view",
  "assistants.manage",
  "subscriptions.view",
  "subscriptions.manage",
  "payments.view",
  "payments.manage",
  "reports.view",
  "settings.center",
] as const satisfies readonly Permission[];

const teacherPermissions = [
  "dashboard.view",
  "students.view",
  "students.view_guardian",
  "guardians.view",
  "guardians.contact",
  "attendance.view",
  "attendance.create",
  "courses.view",
  "groups.view",
  "content.manage",
  "exams.view",
  "exams.manage",
  "results.view",
  "results.manage",
] as const satisfies readonly Permission[];

const assistantPermissions = [
  "dashboard.view",
  "students.view",
  "students.view_guardian",
  "guardians.view",
  "guardians.contact",
  "scanner.use",
  "attendance.view",
  "attendance.create",
  "courses.view",
  "groups.view",
] as const satisfies readonly Permission[];

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  ADMIN: adminPermissions,
  TEACHER: teacherPermissions,
  ASSISTANT: assistantPermissions,
} as const satisfies Record<DashboardRole, readonly Permission[]>;

export const roleLabels = {
  SUPER_ADMIN: "مدير النظام",
  ADMIN: "مدير السنتر",
  TEACHER: "مدرس",
  ASSISTANT: "مساعد تشغيل",
} as const satisfies Record<DashboardRole, string>;
