"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { createContext, useCallback, useContext, useEffect, useState } from "react";
import { apiRequest } from "@/lib/api/client";
import { toApiError } from "@/lib/api/errors";
import { useDashboardWorkspace } from "@/features/dashboard-workspace/workspace-context";
import type { AttendanceRecord, AttendanceScanEvent, AttendanceState, CenterEnrollment, CenterEnrollmentRequest, CenterGroup, CenterSession, EnrollmentBarcode, GuardianMessageDraft, GuardianMessageState, OperationalAuditEntry, StaffStudent } from "@/types/operations";

type RequestAction = "contact" | "waitlist" | "approve" | "assign" | "approve_assign" | "reject" | "cancel";
type Teacher = { id: string; name: string; subject: string }; type Course = { id: string; name: string; teacherId: string };
interface Value { students: StaffStudent[]; enrollments: CenterEnrollment[]; requests: CenterEnrollmentRequest[]; groups: CenterGroup[]; barcodes: EnrollmentBarcode[]; sessions: CenterSession[]; attendance: AttendanceRecord[]; messages: GuardianMessageDraft[]; audit: OperationalAuditEntry[]; scans: AttendanceScanEvent[]; teachers: Teacher[]; courses: Course[]; canSeeTeacher: (teacherId: string, groupId?: string) => boolean; recordContentAudit: (action: string, targetId: string, teacherId?: string) => void; transitionRequest: (id: string, action: RequestAction, groupId?: string, reason?: string, override?: boolean) => string | undefined; assignStudent: (studentId: string, groupId: string, override?: boolean) => string | undefined; removeStudent: (id: string) => string | undefined; transferStudent: (id: string, groupId: string, override?: boolean) => string | undefined; generateBarcode: (id: string) => string | undefined; generateBarcodes: (ids: string[]) => number; revokeBarcode: (id: string) => void; openSession: (groupId: string, maxScore?: number) => string | undefined; scanBarcode: (sessionId: string, value: string, allowOther?: boolean, allowUnexpected?: boolean) => Promise<AttendanceScanEvent["outcome"]>; undoLatestScan: (id: string) => string | undefined; setAttendanceState: (id: string, state: AttendanceState) => void; markRemainingAbsent: (id: string) => void; setMaxScore: (id: string, maxScore?: number, clear?: boolean) => string | undefined; setScore: (id: string, score?: number) => string | undefined; closeSession: (id: string) => string | undefined; reopenSession: (id: string) => void; prepareMessage: (id: string) => void; prepareMessages: (id: string, recordIds?: string[]) => number; updateMessage: (id: string, state: GuardianMessageState, reason?: string) => void; }
interface LoadingValue { loading: boolean; }
const Context = createContext<(Value & LoadingValue) | null>(null);
const n = (value: unknown) => value == null ? undefined : Number(value); const date = (value: unknown) => value ? String(value) : new Date().toISOString();

export function OperationsProvider({ children }: { children: React.ReactNode }) {
  const [loading, setLoading] = useState(true);
  const workspace = useDashboardWorkspace(); const [students, setStudents] = useState<StaffStudent[]>([]); const [enrollments, setEnrollments] = useState<CenterEnrollment[]>([]); const [requests, setRequests] = useState<CenterEnrollmentRequest[]>([]); const [groups, setGroups] = useState<CenterGroup[]>([]); const [barcodes, setBarcodes] = useState<EnrollmentBarcode[]>([]); const [sessions, setSessions] = useState<CenterSession[]>([]); const [attendance, setAttendance] = useState<AttendanceRecord[]>([]); const [messages, setMessages] = useState<GuardianMessageDraft[]>([]); const [scans] = useState<AttendanceScanEvent[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [courses, setCourses] = useState<Course[]>([]); const audit: OperationalAuditEntry[] = [];
  const load = useCallback(async () => {
    const has = (permission: string) => workspace.permissions.includes(permission as never);
    const [studentResponse, enrollmentRaw, requestRaw, groupRaw, barcodeRaw, sessionRaw, messageRaw, courseRaw] = await Promise.all([has("students.view") ? apiRequest<{items:any[]}>("students") : { items: [] }, has("students.view") ? apiRequest<any[]>("center-enrollments") : [], has("center_requests.view") ? apiRequest<any[]>("center-requests") : [], has("groups.view") ? apiRequest<any[]>("groups") : [], has("barcodes.view") ? apiRequest<any[]>("barcodes") : [], has("attendance.view") ? apiRequest<any[]>("attendance-sessions") : [], has("guardian_messages.view") ? apiRequest<any[]>("guardian-messages") : [], has("courses.view") ? apiRequest<any[]>("courses") : []]);
    const studentRaw = studentResponse.items;
    setStudents(studentRaw.map((x) => ({ id: x.id, code: x.studentCode ?? x.code ?? x.id, name: x.name, grade: x.studentProfile?.educationalGrade ?? x.educationalGrade ?? "—", phone: x.phone ?? undefined, guardian: { id: `${x.id}-guardian`, name: x.studentProfile?.guardianName ?? "ولي الأمر", phone: x.studentProfile?.guardianPhone ?? undefined }, active: x.status === "ACTIVE", onlineAccess: "NOT_LINKED" })));
    setEnrollments(enrollmentRaw.map((x) => ({ id: x.id, serial: x.serial, studentId: x.studentId, teacherId: x.teacherId, courseId: x.canonicalCourseId ?? x.courseId, termId: x.academicTermId ?? x.academicTerm, groupId: x.groupId ?? x.group?.id, status: x.status, joinedAt: date(x.createdAt) })));
    setRequests(requestRaw.map((x) => ({ id: x.id, studentId: x.studentId, teacherId: x.teacherId, courseId: x.canonicalCourseId ?? x.courseId, termId: x.academicTermId ?? x.academicTerm, preferredGroupId: x.preferredGroupId ?? x.preferredGroup?.id, status: x.status, submittedAt: date(x.createdAt), reason: x.decisionReason ?? undefined, history: [] })));
    setGroups(groupRaw.map((x) => ({ id: x.id, name: x.name, teacherId: x.teacherId, courseId: x.canonicalCourseId ?? x.courseId, termId: x.academicTermId ?? x.academicTerm, grade: x.academicGrade?.name ?? x.gradeId, active: x.status === "ACTIVE", schedule: { days: Array.isArray(x.schedule?.days) ? x.schedule.days : [], startTime: x.schedule?.startTime ?? "—", durationMinutes: Number(x.schedule?.durationMinutes ?? 0), room: x.location ?? x.schedule?.room ?? "—" }, capacity: { limit: x.capacity, enrolled: x._count?.enrollments ?? x.enrolledCount ?? 0 } })));
    const mappedBarcodes = barcodeRaw.map((x) => ({ id: x.id, enrollmentId: x.enrollmentId, value: x.value ?? undefined, status: x.status, issuedAt: x.issuedAt ?? undefined }));
    setBarcodes(mappedBarcodes.concat(enrollmentRaw.filter((enrollment) => enrollment.status === "ACTIVE" && !mappedBarcodes.some((barcode) => barcode.enrollmentId === enrollment.id)).map((enrollment) => ({ id: `pending-${enrollment.id}`, enrollmentId: enrollment.id, value: undefined, issuedAt: undefined, status: "NOT_GENERATED" as const }))));
    const details = await Promise.all(sessionRaw.map((x) => apiRequest<any>(`attendance-sessions/${x.id}`)));
    const embeddedEnrollments = [...barcodeRaw.map((item) => item.enrollment), ...details.flatMap((item) => (item.records ?? []).map((record:any) => record.enrollment))].filter(Boolean);
    const embeddedStudents = [...requestRaw.map((item) => item.student), ...embeddedEnrollments.map((item) => item.student)].filter(Boolean);
    const embeddedGroups = [...requestRaw.map((item) => item.preferredGroup), ...barcodeRaw.map((item) => item.enrollment?.group), ...details.map((item) => item.group)].filter(Boolean);
    setStudents((current) => current.concat(embeddedStudents.filter((item) => !current.some((student) => student.id === item.id)).map((item) => ({ id: item.id, code: item.studentCode ?? item.id, name: item.name, grade: item.studentProfile?.educationalGrade ?? "—", phone: item.phone ?? undefined, guardian: { id: `${item.id}-guardian`, name: item.studentProfile?.guardianName ?? "ولي الأمر", phone: item.studentProfile?.guardianPhone ?? undefined }, active: item.status === "ACTIVE", onlineAccess: "NOT_LINKED" }))));
    setEnrollments((current) => current.concat(embeddedEnrollments.filter((item) => !current.some((enrollment) => enrollment.id === item.id)).map((item) => ({ id: item.id, serial: item.serial, studentId: item.studentId, teacherId: item.teacherId, courseId: item.canonicalCourseId ?? item.courseId, termId: item.academicTermId ?? item.academicTerm, groupId: item.groupId ?? item.group?.id, status: item.status, joinedAt: date(item.createdAt) }))));
    setGroups((current) => current.concat(embeddedGroups.filter((item) => !current.some((group) => group.id === item.id)).map((item) => ({ id: item.id, name: item.name, teacherId: item.teacherId, courseId: item.canonicalCourseId ?? item.courseId, termId: item.academicTermId ?? item.academicTerm, grade: item.academicGrade?.name ?? item.gradeId, active: item.status === "ACTIVE", schedule: { days: Array.isArray(item.schedule?.days) ? item.schedule.days : [], startTime: item.schedule?.startTime ?? "—", durationMinutes: Number(item.schedule?.durationMinutes ?? 0), room: item.location ?? item.schedule?.room ?? "—" }, capacity: { limit: item.capacity, enrolled: item._count?.enrollments ?? item.enrolledCount ?? 0 } }))));
    setSessions(details.map((x) => ({ id: x.id, groupId: x.groupId, teacherId: x.teacherId ?? x.group?.teacherId, courseId: x.group?.canonicalCourseId ?? x.group?.courseId, date: date(x.sessionDate), status: x.status, maxScore: n(x.maxScore) })));
    setAttendance(details.flatMap((x) => (x.attendanceRecords ?? x.records ?? []).map((r: any) => ({ id: r.id, sessionId: x.id, enrollmentId: r.enrollmentId, state: r.attendance ?? "UNMARKED", scannedAt: r.scannedAt ?? undefined, score: n(r.score), note: r.notes ?? undefined, manual: r.source === "MANUAL" }))));
    setMessages(messageRaw.map((x) => ({ id: x.id, sessionId: x.sessionId, enrollmentId: x.enrollmentId ?? x.attendanceRecord?.enrollmentId, text: x.message ?? x.text, state: x.status, reason: x.failureReason ?? undefined })));
    setCourses(courseRaw.map((x) => ({ id: x.id, name: x.title, teacherId: x.teacherId })));
    const teacherMap = new Map(courseRaw.map((x) => [x.teacher?.id ?? x.teacherId, { id: x.teacher?.id ?? x.teacherId, name: x.teacher?.name ?? "—", subject: x.subject?.name ?? x.subject ?? "—" }])); requestRaw.forEach((item)=>item.teacher&&teacherMap.set(item.teacher.id,{id:item.teacher.id,name:item.teacher.name,subject:"—"})); if(workspace.assignment)teacherMap.set(workspace.assignment.teacherId,{id:workspace.assignment.teacherId,name:workspace.assignment.teacherName,subject:workspace.assignment.subject}); setTeachers([...teacherMap.values()] as Teacher[]);
  }, [workspace.permissions, workspace.assignment]);
  useEffect(() => { setLoading(true); void load().catch((error) => window.alert(toApiError(error).message)).finally(() => setLoading(false)); }, [load]); const refresh = () => { void load(); }; const mutate = (path: string, method = "POST", body?: unknown) => { void apiRequest(path, { method, body }).then(refresh).catch((error) => window.alert(toApiError(error).message)); };
  const canSeeTeacher = (teacherId: string) => workspace.role === "SUPER_ADMIN" || teacherId === (workspace.user.teacherId ?? workspace.assignment?.teacherId);
  const transitionRequest = (id: string, action: RequestAction, groupId?: string, reason?: string) => { const segment = action === "approve_assign" ? "approve-and-assign" : action; mutate(`center-requests/${id}/${segment}`, "POST", action === "assign" || action === "approve_assign" ? { groupId } : action === "reject" ? { reason } : undefined); return undefined; };
  const assignStudent = (studentId: string, groupId: string) => { const g = groups.find((x) => x.id === groupId); if (!g) return "المجموعة غير موجودة."; mutate("center-enrollments", "POST", { studentId, teacherId: g.teacherId, courseId: g.courseId, academicTerm: g.termId, groupId }); return undefined; };
  const removeStudent = (id: string) => { mutate(`center-enrollments/${id}/group`, "DELETE"); return undefined; }; const transferStudent = (id: string, groupId: string) => { mutate(`center-enrollments/${id}/transfer`, "POST", { groupId }); return undefined; };
  const generateBarcode = (id: string) => { const existing=barcodes.find((item)=>item.enrollmentId===id&&!item.id.startsWith("pending-")); if(existing)mutate(`barcodes/${existing.id}/reissue`,"POST");else mutate("barcodes/generate", "POST", { enrollmentId: id }); return undefined; }; const generateBarcodes = (ids: string[]) => { mutate("barcodes/bulk-generate", "POST", { enrollmentIds: ids }); return ids.length; }; const revokeBarcode = (enrollmentId: string) => { const item = barcodes.find((x) => x.enrollmentId === enrollmentId&&!x.id.startsWith("pending-")); if (item) mutate(`barcodes/${item.id}/revoke`); };
  const openSession = (groupId: string, maxScore?: number) => { void apiRequest<any>("attendance-sessions", { method: "POST", body: { groupId, sessionDate: new Date().toISOString(), maxScore } }).then((item) => apiRequest(`attendance-sessions/${item.id}/open`, { method: "POST" })).then(refresh); return undefined; };
  const scanBarcode = async (sessionId: string, value: string, _allowOther?: boolean, allowUnexpected?: boolean) => { try { const result = await apiRequest<{ duplicate: boolean }>(`attendance-sessions/${sessionId}/scan`, { method: "POST", body: { barcodeValue: value, overrideUnexpected: Boolean(allowUnexpected) } }); refresh(); return result.duplicate ? "DUPLICATE" : "SUCCESS"; } catch (error) { const code = toApiError(error).code; if (code === "SESSION_NOT_OPEN") return "CLOSED"; if (code === "UNEXPECTED_ENROLLMENT") return "UNEXPECTED"; if (code === "BARCODE_INVALID" || code === "ENROLLMENT_INACTIVE") return "INVALID"; throw error; } };
  const undoLatestScan = () => "الخادم لا يوفر endpoint للتراجع عن آخر مسح."; const setAttendanceState = (id: string, state: AttendanceState) => { const record = attendance.find((x) => x.id === id); if (record) mutate(`attendance-sessions/${record.sessionId}/records/${id}/attendance`, "PATCH", { attendance: state === "UNMARKED" ? "ABSENT" : state }); }; const markRemainingAbsent = (id: string) => mutate(`attendance-sessions/${id}/mark-remaining-absent`); const setMaxScore = (id: string, maxScore?: number, clearScores?: boolean) => { mutate(`attendance-sessions/${id}/max-score`, "PATCH", { maxScore: maxScore ?? null, clearScores }); return undefined; }; const setScore = (id: string, score?: number) => { const record = attendance.find((x) => x.id === id); if (record) mutate(`attendance-sessions/${record.sessionId}/records/${id}/score`, "PATCH", { score: score ?? null }); return undefined; }; const closeSession = (id: string) => { mutate(`attendance-sessions/${id}/close`); return undefined; }; const reopenSession = (id: string) => mutate(`attendance-sessions/${id}/reopen`);
  const prepareMessage = (id: string) => { const record = attendance.find((x) => x.id === id); if (record) mutate("guardian-messages/prepare", "POST", { sessionId: record.sessionId, attendanceRecordIds: [id], includeScore: true }); }; const prepareMessages = (id: string, recordIds?: string[]) => { mutate("guardian-messages/prepare", "POST", { sessionId: id, attendanceRecordIds: recordIds, allEligible: !recordIds, includeScore: true }); return recordIds?.length ?? 0; }; const updateMessage = (id: string, state: GuardianMessageState, reason?: string) => mutate(`guardian-messages/${id}/status`, "PATCH", { status: state, failureReason: reason });
  return <Context.Provider value={{ loading, students, enrollments, requests, groups, barcodes, sessions, attendance, messages, audit, scans, teachers, courses, canSeeTeacher, recordContentAudit: () => undefined, transitionRequest, assignStudent, removeStudent, transferStudent, generateBarcode, generateBarcodes, revokeBarcode, openSession, scanBarcode, undoLatestScan, setAttendanceState, markRemainingAbsent, setMaxScore, setScore, closeSession, reopenSession, prepareMessage, prepareMessages, updateMessage }}>{children}</Context.Provider>;
}
export function useOperations() { const value = useContext(Context); if (!value) throw new Error("useOperations must be used within OperationsProvider"); return value; }
