"use client";

import { createContext, useContext, useState } from "react";
import { initialAttendance, initialAudit, initialBarcodes, initialEnrollments, initialGroups, initialMessages, initialRequests, initialScans, initialSessions, initialStudents, operationalCourses, operationalTeachers } from "@/mocks/repositories/mock-operations-repository";
import { useDashboardWorkspace } from "@/features/dashboard-workspace/workspace-context";
import type { AttendanceRecord, AttendanceScanEvent, AttendanceState, CenterEnrollment, CenterEnrollmentRequest, CenterGroup, CenterSession, EnrollmentBarcode, GuardianMessageDraft, GuardianMessageState, OperationalAuditEntry, StaffStudent } from "@/types/operations";

type RequestAction = "contact" | "waitlist" | "approve" | "assign" | "approve_assign" | "reject" | "cancel";
interface OperationsContextValue {
  students: StaffStudent[]; enrollments: CenterEnrollment[]; requests: CenterEnrollmentRequest[]; groups: CenterGroup[]; barcodes: EnrollmentBarcode[]; sessions: CenterSession[]; attendance: AttendanceRecord[]; messages: GuardianMessageDraft[]; audit: OperationalAuditEntry[]; scans: AttendanceScanEvent[];
  teachers: typeof operationalTeachers; courses: typeof operationalCourses; canSeeTeacher: (teacherId: string, groupId?: string) => boolean;
  transitionRequest: (id: string, action: RequestAction, groupId?: string, reason?: string, override?: boolean) => string | undefined;
  assignStudent: (studentId: string, groupId: string, override?: boolean) => string | undefined; removeStudent: (enrollmentId: string) => string | undefined; transferStudent: (enrollmentId: string, groupId: string, override?: boolean) => string | undefined;
  generateBarcode: (enrollmentId: string) => string | undefined; generateBarcodes: (ids: string[]) => number; revokeBarcode: (enrollmentId: string) => void;
  openSession: (groupId: string, maxScore?: number) => string | undefined; scanBarcode: (sessionId: string, value: string, allowOtherGroup?: boolean, allowUnexpected?: boolean) => AttendanceScanEvent["outcome"]; undoLatestScan: (sessionId: string) => string | undefined;
  setAttendanceState: (recordId: string, state: AttendanceState) => void; markRemainingAbsent: (sessionId: string) => void; setMaxScore: (sessionId: string, maxScore?: number, clearScores?: boolean) => string | undefined; setScore: (recordId: string, score?: number) => string | undefined;
  closeSession: (sessionId: string) => string | undefined; reopenSession: (sessionId: string) => void; prepareMessage: (recordId: string) => void; prepareMessages: (sessionId: string, recordIds?: string[]) => number; updateMessage: (draftId: string, state: GuardianMessageState, reason?: string) => void;
}
const OperationsContext = createContext<OperationsContextValue | null>(null);
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;

export function OperationsProvider({ children }: { children: React.ReactNode }) {
  const { role, user, assignment } = useDashboardWorkspace();
  const [students] = useState<StaffStudent[]>(initialStudents); const [enrollments, setEnrollments] = useState<CenterEnrollment[]>(initialEnrollments); const [requests, setRequests] = useState<CenterEnrollmentRequest[]>(initialRequests); const [groups, setGroups] = useState<CenterGroup[]>(initialGroups); const [barcodes, setBarcodes] = useState<EnrollmentBarcode[]>(initialBarcodes); const [sessions, setSessions] = useState<CenterSession[]>(initialSessions); const [attendance, setAttendance] = useState<AttendanceRecord[]>(initialAttendance); const [messages, setMessages] = useState<GuardianMessageDraft[]>(initialMessages); const [audit, setAudit] = useState<OperationalAuditEntry[]>(initialAudit); const [scans, setScans] = useState<AttendanceScanEvent[]>(initialScans);
  const canSeeTeacher = (teacherId: string, groupId?: string) => role === "SUPER_ADMIN" || (role === "TEACHER_ADMIN" ? teacherId === user.teacherId : teacherId === assignment?.teacherId && (!groupId || assignment.groups.includes(groups.find((g) => g.id === groupId)?.name ?? "")));
  const recordAudit = (action: string, targetId: string, teacherId?: string) => setAudit((items) => [{ id: id("audit"), action, actorId: user.id, actorRole: role, teacherId, targetId, at: now(), metadata: "محاكاة تشغيلية" }, ...items]);
  const canFit = (group: CenterGroup, override?: boolean) => group.capacity.enrolled < group.capacity.limit || (override && role !== "ASSISTANT");
  const addEnrollment = (studentId: string, group: CenterGroup, action: string) => {
    const enrollment: CenterEnrollment = { id: id("enrollment"), serial: `CE-2601-${Math.floor(Math.random() * 9000 + 1000)}`, studentId, teacherId: group.teacherId, courseId: group.courseId, termId: group.termId, groupId: group.id, status: "ACTIVE", joinedAt: now().slice(0, 10) };
    setEnrollments((items) => [...items, enrollment]); setBarcodes((items) => [...items, { id: id("barcode"), enrollmentId: enrollment.id, status: "NOT_GENERATED" }]); setGroups((items) => items.map((g) => g.id === group.id ? { ...g, capacity: { ...g.capacity, enrolled: g.capacity.enrolled + 1 } } : g)); recordAudit(action, enrollment.id, group.teacherId); return enrollment;
  };
  function transitionRequest(requestId: string, action: RequestAction, groupId?: string, reason?: string, override?: boolean) {
    const request = requests.find((item) => item.id === requestId); if (!request || !canSeeTeacher(request.teacherId)) return "الطلب خارج نطاقك.";
    const allowed: Record<RequestAction, string[]> = { contact: ["PENDING_REVIEW", "WAITLISTED"], waitlist: ["PENDING_REVIEW", "CONTACTED", "APPROVED"], approve: ["PENDING_REVIEW", "CONTACTED", "WAITLISTED"], assign: ["APPROVED"], approve_assign: ["PENDING_REVIEW", "CONTACTED", "WAITLISTED"], reject: ["PENDING_REVIEW", "CONTACTED", "WAITLISTED", "APPROVED"], cancel: ["PENDING_REVIEW", "CONTACTED", "WAITLISTED", "APPROVED"] };
    if (!allowed[action].includes(request.status)) return "هذا الانتقال غير مسموح في الحالة الحالية.";
    if (action === "reject" && !reason?.trim()) return "سبب الرفض مطلوب.";
    let status: CenterEnrollmentRequest["status"] = request.status; let history = "";
    if (action === "contact") { status = "CONTACTED"; history = "تم التواصل"; }
    if (action === "waitlist") { status = "WAITLISTED"; history = "نُقل إلى قائمة الانتظار"; }
    if (action === "approve") { status = "APPROVED"; history = "تمت الموافقة دون تعيين"; }
    if (action === "reject") { status = "REJECTED"; history = `رُفض الطلب: ${reason}`; }
    if (action === "cancel") { status = "CANCELLED"; history = "أُلغي الطلب"; }
    if (action === "assign" || action === "approve_assign") {
      const group = groups.find((g) => g.id === groupId); if (!group || !canSeeTeacher(group.teacherId, group.id) || group.teacherId !== request.teacherId || group.courseId !== request.courseId || group.termId !== request.termId || !canFit(group, override)) return "لا يمكن التعيين إلى المجموعة المختارة.";
      addEnrollment(request.studentId, group, "REQUEST_ASSIGNED"); status = "ASSIGNED"; history = `${action === "approve_assign" ? "تمت الموافقة والتعيين" : "تم التعيين"} إلى ${group.name}${request.preferredGroupId && request.preferredGroupId !== group.id ? " (مختلفة عن التفضيل)" : ""}`;
    }
    setRequests((items) => items.map((item) => item.id === requestId ? { ...item, status, reason: action === "reject" ? reason : item.reason, history: [...item.history, history] } : item)); recordAudit(`REQUEST_${action.toUpperCase()}`, requestId, request.teacherId); return undefined;
  }
  function assignStudent(studentId: string, groupId: string, override?: boolean) { const group = groups.find((g) => g.id === groupId); if (!group || !canSeeTeacher(group.teacherId, group.id) || !canFit(group, override)) return "المجموعة ممتلئة أو خارج نطاقك."; if (enrollments.some((e) => e.studentId === studentId && e.groupId === groupId && e.status === "ACTIVE")) return "الطالب معين بالفعل."; addEnrollment(studentId, group, "GROUP_STUDENT_ASSIGNED"); return undefined; }
  function removeStudent(enrollmentId: string) { const e = enrollments.find((item) => item.id === enrollmentId); if (!e || !canSeeTeacher(e.teacherId, e.groupId)) return "لا يمكن إزالة هذا الطالب."; setEnrollments((items) => items.map((item) => item.id === enrollmentId ? { ...item, groupId: undefined, status: "CANCELLED" } : item)); setGroups((items) => items.map((g) => g.id === e.groupId ? { ...g, capacity: { ...g.capacity, enrolled: Math.max(0, g.capacity.enrolled - 1) } } : g)); recordAudit("GROUP_STUDENT_REMOVED", enrollmentId, e.teacherId); return undefined; }
  function transferStudent(enrollmentId: string, targetId: string, override?: boolean) { const e = enrollments.find((item) => item.id === enrollmentId); const target = groups.find((g) => g.id === targetId); if (!e || !target || !canSeeTeacher(e.teacherId, e.groupId) || !canSeeTeacher(target.teacherId, target.id) || !canFit(target, override)) return "لا يمكن النقل إلى المجموعة المختارة."; if (e.teacherId !== target.teacherId || e.courseId !== target.courseId || e.termId !== target.termId) return "النقل بين نطاقات مختلفة محظور؛ استخدم تدفق التحاق جديد وإصدار باركود جديد."; setEnrollments((items) => items.map((item) => item.id === e.id ? { ...item, groupId: target.id } : item)); setGroups((items) => items.map((g) => g.id === e.groupId ? { ...g, capacity: { ...g.capacity, enrolled: Math.max(0, g.capacity.enrolled - 1) } } : g.id === target.id ? { ...g, capacity: { ...g.capacity, enrolled: g.capacity.enrolled + 1 } } : g)); recordAudit("GROUP_STUDENT_TRANSFERRED", e.id, e.teacherId); return undefined; }
  function generateBarcode(enrollmentId: string) { const e = enrollments.find((item) => item.id === enrollmentId); const barcode = barcodes.find((item) => item.enrollmentId === enrollmentId); if (!e || !barcode || !canSeeTeacher(e.teacherId, e.groupId) || barcode.status === "ACTIVE") return "لا يمكن إنشاء باركود لهذه الحالة."; setBarcodes((items) => items.map((item) => item.id === barcode.id ? { ...item, value: `QCE128-${Math.random().toString(36).slice(2, 10).toUpperCase()}`, status: item.status === "REVOKED" ? "REISSUED" : "ACTIVE", issuedAt: now() } : item)); recordAudit("BARCODE_GENERATED", enrollmentId, e.teacherId); return undefined; }
  function generateBarcodes(ids: string[]) { let count = 0; ids.forEach((enrollmentId) => { const barcode = barcodes.find((item) => item.enrollmentId === enrollmentId); if (barcode?.status === "NOT_GENERATED" && !generateBarcode(enrollmentId)) count += 1; }); return count; }
  function revokeBarcode(enrollmentId: string) { const e = enrollments.find((item) => item.id === enrollmentId); if (!e || !canSeeTeacher(e.teacherId, e.groupId)) return; setBarcodes((items) => items.map((item) => item.enrollmentId === enrollmentId ? { ...item, status: "REVOKED" } : item)); recordAudit("BARCODE_REVOKED", enrollmentId, e.teacherId); }
  function openSession(groupId: string, maxScore?: number) { const g = groups.find((item) => item.id === groupId); if (!g || !canSeeTeacher(g.teacherId, g.id) || (maxScore !== undefined && maxScore <= 0)) return "تعذر فتح الجلسة بالبيانات الحالية."; const sessionId = id("session"); setSessions((items) => [{ id: sessionId, groupId, teacherId: g.teacherId, courseId: g.courseId, date: now(), status: "OPEN", maxScore }, ...items]); setAttendance((items) => [...items, ...enrollments.filter((e) => e.groupId === groupId && e.status === "ACTIVE").map((e) => ({ id: id("attendance"), sessionId, enrollmentId: e.id, state: "UNMARKED" as const }))]); recordAudit("SESSION_OPENED", sessionId, g.teacherId); return undefined; }
  function scanBarcode(sessionId: string, value: string, allowOtherGroup = false, allowUnexpected = false) { const session = sessions.find((item) => item.id === sessionId); const barcode = barcodes.find((item) => item.value === value); const enrollment = barcode && enrollments.find((item) => item.id === barcode.enrollmentId); let record = barcode && attendance.find((item) => item.sessionId === sessionId && item.enrollmentId === barcode.enrollmentId); let outcome: AttendanceScanEvent["outcome"] = "INVALID"; if (!session || session.status !== "OPEN") outcome = "CLOSED"; else if (!barcode || !enrollment) outcome = "INVALID"; else if (barcode.status === "REVOKED") outcome = "REVOKED"; else if (enrollment.teacherId !== session.teacherId || enrollment.courseId !== session.courseId || enrollment.termId !== groups.find((g) => g.id === session.groupId)?.termId) outcome = "WRONG_SCOPE"; else if (!record && enrollment.groupId !== session.groupId && !allowOtherGroup) outcome = "OTHER_GROUP"; else if (!record && !allowUnexpected) outcome = "UNEXPECTED"; else { if (!record) { record = { id: id("attendance"), sessionId, enrollmentId: enrollment.id, state: "UNMARKED" }; setAttendance((items) => [...items, record!]); } if (record.state !== "UNMARKED") outcome = "DUPLICATE"; else { outcome = "SUCCESS"; setAttendance((items) => items.map((item) => item.id === record!.id ? { ...item, state: "PRESENT", scannedAt: now() } : item)); recordAudit("ATTENDANCE_SCANNED", record.id, session.teacherId); } } setScans((items) => [{ id: id("scan"), sessionId, barcodeValue: value, outcome, at: now(), enrollmentId: enrollment?.id }, ...items].slice(0, 12)); return outcome; }
  function undoLatestScan(sessionId: string) { const scan = scans.find((item) => item.sessionId === sessionId && item.outcome === "SUCCESS" && item.enrollmentId); if (!scan) return "لا يوجد مسح ناجح يمكن التراجع عنه."; setAttendance((items) => items.map((item) => item.sessionId === sessionId && item.enrollmentId === scan.enrollmentId ? { ...item, state: "UNMARKED", scannedAt: undefined } : item)); setScans((items) => items.filter((item) => item.id !== scan.id)); recordAudit("ATTENDANCE_SCAN_UNDONE", scan.enrollmentId!); return undefined; }
  function setAttendanceState(recordId: string, state: AttendanceState) { const record = attendance.find((item) => item.id === recordId); const session = record && sessions.find((item) => item.id === record.sessionId); if (!record || !session || !canSeeTeacher(session.teacherId, session.groupId)) return; setAttendance((items) => items.map((item) => item.id === recordId ? { ...item, state, manual: true } : item)); recordAudit("ATTENDANCE_CHANGED", recordId, session.teacherId); }
  function markRemainingAbsent(sessionId: string) { setAttendance((items) => items.map((item) => item.sessionId === sessionId && item.state === "UNMARKED" ? { ...item, state: "ABSENT" as const, manual: true } : item)); recordAudit("ATTENDANCE_REMAINING_ABSENT", sessionId); }
  function setMaxScore(sessionId: string, maxScore?: number, clearScores = false) { if (maxScore !== undefined && maxScore <= 0) return "الدرجة النهائية يجب أن تكون أكبر من صفر."; const records = attendance.filter((item) => item.sessionId === sessionId); if (maxScore !== undefined && records.some((item) => item.score !== undefined && item.score > maxScore)) return "هناك درجات أعلى من الدرجة النهائية الجديدة."; if (maxScore === undefined && records.some((item) => item.score !== undefined) && !clearScores) return "تأكيد مسح الدرجات مطلوب."; if (maxScore === undefined) setAttendance((items) => items.map((item) => item.sessionId === sessionId ? { ...item, score: undefined } : item)); setSessions((items) => items.map((item) => item.id === sessionId ? { ...item, maxScore } : item)); recordAudit(maxScore === undefined ? "MAX_SCORE_AND_SCORES_CLEARED" : "MAX_SCORE_CHANGED", sessionId); return undefined; }
  function setScore(recordId: string, score?: number) { const record = attendance.find((item) => item.id === recordId); const session = record && sessions.find((item) => item.id === record.sessionId); if (!record || !session || !canSeeTeacher(session.teacherId, session.groupId) || (score !== undefined && (score < 0 || session.maxScore === undefined || score > session.maxScore))) return "الدرجة يجب أن تكون بين صفر والدرجة النهائية."; setAttendance((items) => items.map((item) => item.id === recordId ? { ...item, score } : item)); recordAudit("STUDENT_SCORE_CHANGED", recordId, session.teacherId); return undefined; }
  function closeSession(sessionId: string) { if (attendance.some((item) => item.sessionId === sessionId && item.state === "UNMARKED")) return "راجع الطلاب غير المحددين أو حدّدهم غائبين أولًا."; setSessions((items) => items.map((item) => item.id === sessionId ? { ...item, status: "CLOSED" } : item)); recordAudit("SESSION_CLOSED", sessionId); return undefined; }
  function reopenSession(sessionId: string) { setSessions((items) => items.map((item) => item.id === sessionId ? { ...item, status: "REVIEW" } : item)); recordAudit("SESSION_REOPENED", sessionId); }
  function prepareMessage(recordId: string) { const record = attendance.find((item) => item.id === recordId); if (!record || messages.some((item) => item.enrollmentId === record.enrollmentId && item.sessionId === record.sessionId)) return; const enrollment = enrollments.find((item) => item.id === record.enrollmentId); const student = enrollment && students.find((item) => item.id === enrollment.studentId); const session = sessions.find((item) => item.id === record.sessionId); const teacher = session && operationalTeachers.find((item) => item.id === session.teacherId); if (!enrollment || !student || !session || !teacher) return; const stateText = record.state === "ABSENT" ? "لم يحضر" : record.state === "LATE" ? "حضر متأخرًا" : "تم تسجيل حضوره"; const score = session.maxScore !== undefined && record.score !== undefined ? ` وحصل على ${record.score} من ${session.maxScore}` : ""; setMessages((items) => [...items, { id: id("message"), sessionId: session.id, enrollmentId: enrollment.id, text: `الطالب ${student.name} ${stateText} في حصة ${teacher.subject}${score} بتاريخ ${session.date.slice(0, 10)}.`, state: student.guardian.phone ? "READY" : "FAILED", reason: student.guardian.phone ? undefined : "رقم ولي الأمر غير متاح أو غير صالح" }]); recordAudit("MESSAGE_PREPARED", record.id, session.teacherId); }
  function prepareMessages(sessionId: string, recordIds?: string[]) { const records = attendance.filter((r) => r.sessionId === sessionId && (!recordIds || recordIds.includes(r.id))); const before = messages.length; records.forEach((r) => prepareMessage(r.id)); return Math.max(0, records.length - (messages.length - before)); }
  function updateMessage(draftId: string, state: GuardianMessageState, reason?: string) { setMessages((items) => items.map((item) => item.id === draftId ? { ...item, state, reason } : item)); recordAudit(`MESSAGE_${state}`, draftId); }
  return <OperationsContext.Provider value={{ students, enrollments, requests, groups, barcodes, sessions, attendance, messages, audit, scans, teachers: operationalTeachers, courses: operationalCourses, canSeeTeacher, transitionRequest, assignStudent, removeStudent, transferStudent, generateBarcode, generateBarcodes, revokeBarcode, openSession, scanBarcode, undoLatestScan, setAttendanceState, markRemainingAbsent, setMaxScore, setScore, closeSession, reopenSession, prepareMessage, prepareMessages, updateMessage }}>{children}</OperationsContext.Provider>;
}
export function useOperations() { const context = useContext(OperationsContext); if (!context) throw new Error("useOperations must be used within OperationsProvider"); return context; }
