"use client";
/* eslint-disable @typescript-eslint/no-unused-vars */
import {createContext,useContext} from "react";
import {brandConfig} from "@/config/brand";
import {useOperations} from "@/features/operations/operations-context";
import type{AssignmentDraft,AssistantProfile,DashboardSettings,TeacherProfile}from"@/types/staff";
type Value={teachers:TeacherProfile[];assistants:AssistantProfile[];settings:DashboardSettings;canSeeTeacher:(id:string)=>boolean;createTeacher:(x:Omit<TeacherProfile,"id">)=>string|undefined;updateTeacher:(id:string,x:Partial<TeacherProfile>)=>string|undefined;setTeacherStatus:(id:string,s:TeacherProfile["status"])=>string|undefined;createAssistant:(x:Omit<AssistantProfile,"id">)=>string|undefined;updateAssistant:(id:string,x:Partial<AssistantProfile>)=>string|undefined;setAssistantStatus:(id:string,s:AssistantProfile["status"])=>string|undefined;createAssignment:(x:AssignmentDraft)=>string|undefined;updateAssignment:(id:string,x:AssignmentDraft)=>string|undefined;copyAssignment:(id:string,a:string,t:string)=>string|undefined;suspendAssignment:(id:string)=>string|undefined;updateSettings:(x:Partial<DashboardSettings>)=>string|undefined};const Context=createContext<Value|null>(null);const blocker="الخادم لا يوفر عقد إدارة الموظفين أو التعيينات أو الإعدادات لهذه العملية؛ الواجهة للعرض فقط.";
export function StaffProvider({children}:{children:React.ReactNode}){const ops=useOperations();const teachers:TeacherProfile[]=ops.teachers.map(t=>({id:t.id,name:t.name,subject:t.subject,grades:[],courseIds:ops.courses.filter(c=>c.teacherId===t.id).map(c=>c.id),groupIds:ops.groups.filter(g=>g.teacherId===t.id).map(g=>g.id),status:"ACTIVE"}));const assistants:AssistantProfile[]=[];const settings:DashboardSettings={brandName:brandConfig.name,shortName:brandConfig.shortName,centerName:brandConfig.centerName,supportEmail:brandConfig.support.email,supportPhone:brandConfig.support.phone,whatsapp:brandConfig.support.whatsapp,websiteUrl:brandConfig.url,currentTerm:"—",attendanceDefaultMinutes:90,guardianTemplate:"—",studentSessionPolicy:"—",staffSessionPolicy:"تُحل الصلاحيات والنطاق من جلسة الخادم.",logoSrc:brandConfig.markSrc};const unsupported=()=>blocker;const unsupportedWithInput=(_input:unknown)=>blocker;const unsupportedTwo=(_id:string,_input:unknown)=>blocker;return <Context.Provider value={{teachers,assistants,settings,canSeeTeacher:ops.canSeeTeacher,createTeacher:unsupportedWithInput,updateTeacher:unsupportedTwo,setTeacherStatus:unsupportedTwo,createAssistant:unsupportedWithInput,updateAssistant:unsupportedTwo,setAssistantStatus:unsupportedTwo,createAssignment:unsupportedWithInput,updateAssignment:unsupportedTwo,copyAssignment:(_id:string,_a:string,_t:string)=>blocker,suspendAssignment:unsupported,updateSettings:unsupportedWithInput}}>{children}</Context.Provider>}
export function useStaff(){const value=useContext(Context);if(!value)throw new Error("useStaff must be used within StaffProvider");return value;}
