"use client";

import { createContext, useContext, useState } from "react";
import { canAccess } from "@/lib/access-control";
import { useContent } from "@/features/content/content-context";
import { useDashboardWorkspace } from "@/features/dashboard-workspace/workspace-context";
import { useOperations } from "@/features/operations/operations-context";
import { initialAssistantProfiles, initialDashboardSettings, initialTeacherProfiles } from "@/mocks/repositories/mock-staff-repository";
import type { AssistantAssignment } from "@/types/auth";
import type { Permission } from "@/types/permissions";
import type { AssignmentDraft, AssistantProfile, DashboardSettings, TeacherProfile } from "@/types/staff";

type StaffContextValue = {
  teachers: TeacherProfile[]; assistants: AssistantProfile[]; settings: DashboardSettings;
  canSeeTeacher: (id: string) => boolean; createTeacher: (input: Omit<TeacherProfile, "id">) => string | undefined; updateTeacher: (id: string, input: Partial<TeacherProfile>) => string | undefined; setTeacherStatus: (id: string, status: TeacherProfile["status"]) => string | undefined;
  createAssistant: (input: Omit<AssistantProfile, "id">) => string | undefined; updateAssistant: (id: string, input: Partial<AssistantProfile>) => string | undefined; setAssistantStatus: (id: string, status: AssistantProfile["status"]) => string | undefined;
  createAssignment: (input: AssignmentDraft) => string | undefined; updateAssignment: (id: string, input: AssignmentDraft) => string | undefined; copyAssignment: (id: string, assistantId: string, teacherId: string) => string | undefined; suspendAssignment: (id: string) => string | undefined; updateSettings: (input: Partial<DashboardSettings>) => string | undefined;
};
const StaffContext = createContext<StaffContextValue | null>(null);
const makeId = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;

export function StaffProvider({ children }: { children: React.ReactNode }) {
  const { role, user, permissions, assignments, upsertAssignment, suspendAssignment: suspendWorkspaceAssignment } = useDashboardWorkspace(); const ops = useOperations(); const content = useContent();
  const [teachers, setTeachers] = useState(initialTeacherProfiles); const [assistants, setAssistants] = useState(initialAssistantProfiles); const [settings, setSettings] = useState(initialDashboardSettings);
  const allowed = (permission: Permission) => canAccess(role, permission, permissions); const canSeeTeacher = (teacherId: string) => role === "SUPER_ADMIN" || (role === "TEACHER_ADMIN" && teacherId === user.teacherId);
  const audit = (action: string, targetId: string, teacherId?: string) => ops.recordContentAudit(action, targetId, teacherId);
  function createTeacher(input: Omit<TeacherProfile, "id">) { if (!allowed("teachers.manage") || !input.name.trim()) return "لا تملك صلاحية إنشاء مدرس أو البيانات ناقصة."; const item = { ...input, id: makeId("teacher") }; setTeachers((items) => [...items, item]); audit("TEACHER_CREATED", item.id, item.id); return undefined; }
  function updateTeacher(id: string, input: Partial<TeacherProfile>) { const item = teachers.find((teacher) => teacher.id === id); if (!item || !allowed("teachers.manage") || !canSeeTeacher(id)) return "المدرس غير موجود أو خارج نطاقك."; setTeachers((items) => items.map((teacher) => teacher.id === id ? { ...teacher, ...input, id } : teacher)); audit("TEACHER_UPDATED", id, id); return undefined; }
  function setTeacherStatus(id: string, status: TeacherProfile["status"]) { const result = updateTeacher(id, { status }); if (!result) audit(status === "ACTIVE" ? "TEACHER_ACTIVATED" : "TEACHER_SUSPENDED", id, id); return result; }
  function createAssistant(input: Omit<AssistantProfile, "id">) { if (!allowed("assistants.manage") || !input.name.trim() || !input.email.includes("@")) return "تحقق من اسم المساعد وبريده وصلاحيتك."; const item = { ...input, id: makeId("assistant") }; setAssistants((items) => [...items, item]); audit("ASSISTANT_CREATED", item.id); return undefined; }
  function updateAssistant(id: string, input: Partial<AssistantProfile>) { const item = assistants.find((assistant) => assistant.id === id); if (!item || !allowed("assistants.manage")) return "المساعد غير موجود أو لا تملك صلاحية تعديله."; const ownsAssignment = assignments.some((assignment) => assignment.assistantId === id && canSeeTeacher(assignment.teacherId)); if (role === "TEACHER_ADMIN" && !ownsAssignment) return "المساعد خارج مساحة عمل المدرس."; setAssistants((items) => items.map((assistant) => assistant.id === id ? { ...assistant, ...input, id } : assistant)); audit("ASSISTANT_UPDATED", id); return undefined; }
  function setAssistantStatus(id: string, status: AssistantProfile["status"]) { const result = updateAssistant(id, { status }); if (!result) audit(status === "ACTIVE" ? "ASSISTANT_ACTIVATED" : "ASSISTANT_SUSPENDED", id); return result; }
  function validateAssignment(input: AssignmentDraft) { const assistant = assistants.find((item) => item.id === input.assistantId && item.status === "ACTIVE"); const teacher = teachers.find((item) => item.id === input.teacherId && item.status === "ACTIVE"); return Boolean(assistant && teacher && canSeeTeacher(input.teacherId) && input.courses.every((courseId) => teacher.courseIds.includes(courseId) && content.courses.some((course) => course.id === courseId && course.teacherId === input.teacherId)) && input.groups.every((groupId) => teacher.groupIds.includes(groupId) && ops.groups.some((group) => group.id === groupId && group.teacherId === input.teacherId)) && input.grades.every((grade) => teacher.grades.includes(grade))); }
  function toAssignment(id: string, input: AssignmentDraft): AssistantAssignment { const teacher = teachers.find((item) => item.id === input.teacherId)!; return { id, assistantId: input.assistantId, teacherId: input.teacherId, teacherName: teacher.name, subject: teacher.subject, courses: input.courses, grades: input.grades, groups: input.groups.map((id) => ops.groups.find((group) => group.id === id)?.name ?? id), permissions: input.permissions, active: true }; }
  function createAssignment(input: AssignmentDraft) { if (!allowed("assignments.manage") || !validateAssignment(input)) return "الربط أو نطاق المدرس/الكورس/المجموعة غير صالح."; if (assignments.some((item) => item.assistantId === input.assistantId && item.teacherId === input.teacherId && item.active !== false)) return "للمساعد تعيين نشط لهذا المدرس بالفعل."; const item = toAssignment(makeId("assignment"), input); upsertAssignment(item); audit("ASSIGNMENT_CREATED", item.id, item.teacherId); return undefined; }
  function updateAssignment(id: string, input: AssignmentDraft) { const existing = assignments.find((item) => item.id === id); if (!existing || !allowed("assignments.manage") || role === "ASSISTANT" || !canSeeTeacher(existing.teacherId) || !validateAssignment(input)) return "التعيين غير صالح أو خارج نطاقك."; upsertAssignment({ ...toAssignment(id, input), active: existing.active !== false }); audit("ASSIGNMENT_UPDATED", id, input.teacherId); return undefined; }
  function copyAssignment(id: string, assistantId: string, teacherId: string) { const source = assignments.find((item) => item.id === id); if (!source) return "التعيين المصدر غير موجود."; const targetTeacher = teachers.find((item) => item.id === teacherId); if (!targetTeacher) return "المدرس الهدف غير موجود."; return createAssignment({ assistantId, teacherId, courses: targetTeacher.courseIds, grades: targetTeacher.grades, groups: targetTeacher.groupIds, permissions: [...source.permissions] }); }
  function suspendAssignment(id: string) { const item = assignments.find((assignment) => assignment.id === id); if (!item || !allowed("assignments.manage") || role === "ASSISTANT" || !canSeeTeacher(item.teacherId)) return "لا يمكن إيقاف هذا التعيين."; suspendWorkspaceAssignment(id); audit("ASSIGNMENT_SUSPENDED", id, item.teacherId); return undefined; }
  function updateSettings(input: Partial<DashboardSettings>) { if (!allowed("settings.center") && !allowed("settings.system")) return "لا تملك صلاحية الإعدادات."; setSettings((current) => ({ ...current, ...input })); audit("DASHBOARD_SETTINGS_UPDATED", "settings"); return undefined; }
  return <StaffContext.Provider value={{ teachers, assistants, settings, canSeeTeacher, createTeacher, updateTeacher, setTeacherStatus, createAssistant, updateAssistant, setAssistantStatus, createAssignment, updateAssignment, copyAssignment, suspendAssignment, updateSettings }}>{children}</StaffContext.Provider>;
}
export function useStaff() { const context = useContext(StaffContext); if (!context) throw new Error("useStaff must be used within StaffProvider"); return context; }
