"use client";

import { useEffect, useState } from "react";
import { AccessDeniedState } from "@/components/shared/access-denied-state";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useContent } from "@/features/content/content-context";
import { useDashboardWorkspace } from "@/features/dashboard-workspace/workspace-context";
import { useFinance } from "@/features/finance/finance-context";
import { useStaff } from "@/features/staff/staff-context";
import { apiRequest } from "@/lib/api/client";
import { toApiError } from "@/lib/api/errors";
import { canAccess } from "@/lib/access-control";
import type { DashboardSettings } from "@/types/staff";

type OperationalSummary = { enrollmentCount: number; groupCount: number; occupiedSeats: number; attendanceCount: number; scoredAttendanceCount: number; courses: { title: string; status: string }[]; assistants: { name: string; status: string }[]; guardianMessages: { id: string; status: string }[]; groupCapacities: { name: string; enrolled: number; capacity: number }[] };
type AuditItem = { id: string; action: string; entityType: string; entityId: string; createdAt: string; actor?: { name: string } };

function Metric({ label, value, helper }: { label: string; value: string | number; helper?: string }) { return <Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p>{helper ? <p className="mt-1 text-xs text-muted-foreground">{helper}</p> : null}</CardContent></Card>; }
function ReportList({ title, items }: { title: string; items: string[] }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-2">{items.length ? items.map((item, index) => <p key={`${item}-${index}`} className="rounded border p-2 text-sm">{item}</p>) : <p className="text-sm text-muted-foreground">لا توجد بيانات ضمن الفلتر.</p>}</CardContent></Card>; }

export function ReportsPage() {
  const content = useContent(); const finance = useFinance(); const staff = useStaff(); const { role, permissions } = useDashboardWorkspace();
  const [scope, setScope] = useState<"operational" | "financial">("operational"); const [teacherId, setTeacherId] = useState("ALL"); const [operational, setOperational] = useState<OperationalSummary>();
  useEffect(() => { if (canAccess(role, "reports.view", permissions)) void apiRequest<OperationalSummary>(`operational-reports/summary${teacherId === "ALL" ? "" : `?teacherId=${encodeURIComponent(teacherId)}`}`).then(setOperational).catch((error) => window.alert(toApiError(error).message)); }, [teacherId, role, permissions]);
  if (!canAccess(role, "reports.view", permissions)) return <AccessDeniedState />;
  const payments = finance.payments.filter((item) => finance.canSeePayment(item) && (teacherId === "ALL" || item.teacherId === teacherId)); const entitlements = finance.entitlements.filter((item) => finance.canSeeEntitlement(item) && (teacherId === "ALL" || item.teacherId === teacherId)); const approved = payments.filter((item) => item.status === "APPROVED"); const packages = new Map<string, number>(); approved.forEach((item) => packages.set(item.packageId, (packages.get(item.packageId) ?? 0) + 1)); const financial = canAccess(role, "reports.financial", permissions); const summary = teacherId === "ALL" ? finance.financialSummary : undefined; const approvedAmount = summary?.approvedAmount ?? approved.reduce((sum, item) => sum + item.amount, 0); const pendingCount = summary?.byStatus.PENDING_REVIEW ?? payments.filter((item) => item.status === "PENDING_REVIEW").length; const rejectedCount = summary?.byStatus.REJECTED ?? payments.filter((item) => item.status === "REJECTED").length;
  return <><PageHeader title="التقارير" description="ملخصات تشغيلية ومالية صادرة مباشرة من الخادم ضمن النطاق الحالي." /><main className="space-y-4 px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-wrap gap-2"><Button variant={scope === "operational" ? "default" : "outline"} onClick={() => setScope("operational")}>تشغيلية</Button>{financial ? <Button variant={scope === "financial" ? "default" : "outline"} onClick={() => setScope("financial")}>مالية</Button> : null}<select value={teacherId} onChange={(event) => setTeacherId(event.target.value)} className="h-10 rounded-lg border bg-card px-3"><option value="ALL">كل النطاق المتاح</option>{staff.teachers.filter((teacher) => staff.canSeeTeacher(teacher.id)).map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></div>{scope === "operational" ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="الطلاب والالتحاقات" value={operational?.enrollmentCount ?? 0} helper="التحاق سنتر فقط" /><Metric label="المجموعات" value={operational?.groupCount ?? 0} helper={`${operational?.occupiedSeats ?? 0} مقعد مشغول`} /><Metric label="الحضور" value={operational?.attendanceCount ?? 0} helper="سجلات جلسات" /><Metric label="درجات الجلسات" value={operational?.scoredAttendanceCount ?? 0} helper="من الحضور فقط" /></div><div className="grid gap-3 lg:grid-cols-2"><ReportList title="المحتوى والنشر" items={(operational?.courses ?? []).map((item) => `${item.title} · ${item.status}`)} /><ReportList title="المساعدون" items={(operational?.assistants ?? []).map((item) => `${item.name} · ${item.status}`)} /><ReportList title="الرسائل لأولياء الأمور" items={(operational?.guardianMessages ?? []).map((item) => `${item.status} · ${item.id}`)} /><ReportList title="سعات المجموعات" items={(operational?.groupCapacities ?? []).map((item) => `${item.name}: ${item.enrolled}/${item.capacity}`)} /></div></> : <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="مدفوعات معتمدة" value={`${approvedAmount} ج.م`} /><Metric label="قيد المراجعة" value={pendingCount} /><Metric label="مرفوضة" value={rejectedCount} /><Metric label="صلاحيات إلكترونية" value={entitlements.length} helper="منفصلة عن الالتحاق السنتر" /></div><div className="grid gap-3 lg:grid-cols-2"><ReportList title="طرق الدفع" items={Object.entries(payments.reduce<Record<string, number>>((result, item) => ({ ...result, [item.method]: (result[item.method] ?? 0) + item.amount }), {})).map(([method, total]) => `${method}: ${total} ج.م`)} /><ReportList title="مبيعات الباقات المعتمدة" items={[...packages.entries()].map(([id, count]) => `${content.packages.find((item) => item.id === id)?.title ?? id}: ${count}`)} /><ReportList title="استخدام الكوبونات والأكواد" items={[`كوبونات مستردة: ${finance.coupons.filter((item) => item.status === "REDEEMED").length}`, `أكواد مجانية مستردة: ${finance.accessCodes.filter((item) => item.status === "REDEEMED").length}`]} /></div></>}</main></>;
}

export function AuditLogPage() {
  const { role, permissions } = useDashboardWorkspace(); const [items, setItems] = useState<AuditItem[]>([]);
  useEffect(() => { if (canAccess(role, "audit.view", permissions)) void apiRequest<{ items: AuditItem[] }>("audit-log?limit=50").then((response) => setItems(response.items)).catch((error) => window.alert(toApiError(error).message)); }, [role, permissions]);
  if (!canAccess(role, "audit.view", permissions)) return <AccessDeniedState />;
  return <><PageHeader title="سجل العمليات" description="آخر العمليات الحساسة ضمن النطاق المسموح من الخادم." /><main className="space-y-2 px-4 py-6 sm:px-6 lg:px-8">{items.map((item) => <Card key={item.id}><CardContent className="flex flex-wrap justify-between gap-2 p-4 text-sm"><span><strong>{item.action}</strong> · {item.entityType} · {item.entityId}</span><span className="text-muted-foreground">{item.actor?.name ?? "النظام"} · {item.createdAt.slice(0, 16)}</span></CardContent></Card>)}</main></>;
}

export function SettingsPage() {
  const staff = useStaff(); const finance = useFinance(); const { role, permissions } = useDashboardWorkspace(); const [draft, setDraft] = useState<DashboardSettings>(); const [notice, setNotice] = useState(""); const canCenter = canAccess(role, "settings.center", permissions) || canAccess(role, "settings.system", permissions); const editable = canAccess(role, "settings.system", permissions); const settings = draft ?? staff.settings;
  if (!canCenter) return <AccessDeniedState />;
  const field = (key: keyof DashboardSettings) => (event: React.ChangeEvent<HTMLInputElement>) => setDraft({ ...settings, [key]: key === "attendanceDefaultMinutes" ? Number(event.target.value) : event.target.value });
  return <><PageHeader title="الإعدادات" description="إعدادات المنصة المحفوظة في الخادم؛ التعديل العام متاح للمشرف العام فقط." /><main className="space-y-4 px-4 py-6 sm:px-6 lg:px-8">{notice ? <p role="status" className="rounded-lg bg-secondary p-3 text-sm">{notice}</p> : null}<fieldset disabled={!editable}><Card><CardHeader><CardTitle>الهوية والتواصل</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input value={settings.brandName} onChange={field("brandName")} /><Input value={settings.shortName} onChange={field("shortName")} /><Input value={settings.centerName} onChange={field("centerName")} /><Input value={settings.websiteUrl} onChange={field("websiteUrl")} /><Input value={settings.supportEmail} onChange={field("supportEmail")} /><Input value={settings.supportPhone} onChange={field("supportPhone")} /><Input value={settings.whatsapp} onChange={field("whatsapp")} /><Input value={settings.currentTerm} onChange={field("currentTerm")} /><Input value={settings.attendanceDefaultMinutes} onChange={field("attendanceDefaultMinutes")} inputMode="numeric" /></CardContent></Card></fieldset><Card><CardHeader><CardTitle>وجهات الدفع المركزية</CardTitle></CardHeader><CardContent className="space-y-2">{finance.destinations.map((item) => <p key={item.id} className="rounded border p-2 text-sm">{item.provider} · {item.address} · {item.active ? "نشط" : "متوقف"}</p>)}</CardContent></Card>{editable ? <Button onClick={() => setNotice(staff.updateSettings(settings) ?? "تم إرسال الإعدادات للحفظ.")}>حفظ الإعدادات</Button> : null}</main></>;
}
